require: 'ts-node/register'
timeout: '120000'
reporter: 'min'
reporter-option:
  - 'cdn=true'
  - 'json=false'
exit: true
spec: ['test/unit/*.ts', 'test/unit/**/*.ts', 'test/v2/unit/*.ts', 'test/v2/unit/**/*.ts']
