import type { UnderlyingAsset } from '../base';
import * as AccountCtors from '../ofc';
export const botOfcTokens = [
  AccountCtors.ofcerc20(
    '26f46d44-700d-4e32-8845-fb181e6d8027',
    'ofceth:gusdcq',
    'Galaxy USDC Quality',
    18,
    'eth:gusdcq' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '336f05ca-6548-495e-9c0b-8deba95ea56b',
    'ofceth:gusdtq',
    'Galaxy USDT Quality',
    18,
    'eth:gusdtq' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '0c881f11-064e-4e54-9fa6-55406e419819',
    'ofceth:gwethq',
    'Galaxy WETH Quality',
    18,
    'eth:gwethq' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'f8ffca6e-a6dc-4d14-90d8-500383cdbffe',
    'ofceth:acu',
    'Acurast',
    12,
    'eth:acu' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '1a446703-1f79-4212-8ee2-5338515708d3',
    'ofceth:obol',
    'Obol',
    18,
    'eth:obol' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '6b42cbcb-1eba-4c20-be8b-f94e878f5365',
    'ofceth:re',
    'Re Protocol',
    18,
    'eth:re' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '186594ec-8433-46db-9756-f071c172fa67',
    'ofceth:filqa',
    'Fidelity USD Digital Liquidity Fund-Acc',
    2,
    'eth:filqa' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'b28d8ff5-a32a-44db-b1b1-c3b9f9a949c3',
    'ofceth:filqd',
    'Fidelity USD Digital Liquidity Fund-Dist',
    2,
    'eth:filqd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'bc9074f8-e75b-4daf-9305-1c1d31127264',
    'ofceth:wylds',
    'Hastra wYLDS',
    6,
    'eth:wylds' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '4451adc0-9d86-4518-87bf-fcaaf8fa43e8',
    'ofceth:hprime',
    'Hastra PRIME',
    6,
    'eth:hprime' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '8cfa782a-c177-4501-9af6-84423eeb2017',
    'ofceth:bill',
    'Billions Network',
    18,
    'eth:bill' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '4b5a115f-534e-4cd7-befc-9e432b6fe3c4',
    'ofceth:frnt',
    'Frontier Stable Token',
    6,
    'eth:frnt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '4f06be6b-081c-45cd-8d13-77f88e735ebc',
    'ofceth:usdds',
    'Usdd Stablecoin',
    18,
    'eth:usdds' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'b8f267b6-9060-4ca8-ae30-11d77a665d88',
    'ofceth:lbtc',
    'Lombard Staked BTC',
    8,
    'eth:lbtc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'fec0468d-29fa-4dcf-af02-4e63d434c9ad',
    'ofceth:usdai',
    'USDai',
    18,
    'eth:usdai' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '2ff046d0-12bf-4e67-a3e9-b974e99566a5',
    'ofceth:susdai',
    'Staked USDai',
    18,
    'eth:susdai' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'e6c700dc-6313-44e0-b4e9-b482d734f1cb',
    'ofceth:nvprime',
    'Nuva Prime Vault',
    18,
    'eth:nvprime' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'b4472153-1f02-45aa-b1b3-9a5793b2a5ae',
    'ofceth:king',
    'King Protocol',
    18,
    'eth:king' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'c9ab646b-209b-418b-8086-7c9a6c078068',
    'ofceth:valt',
    'VALT Token',
    18,
    'eth:valt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '549fa391-e575-49fc-971d-1ba42b90019f',
    'ofceth:myrt',
    'MYR Stablecoin',
    6,
    'eth:myrt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'fce95d17-085b-40f5-90a2-6eacb619a112',
    'ofceth:sent',
    'Sentient',
    18,
    'eth:sent' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'e7fb9bbd-e72d-4863-9aad-a851ac00c7c5',
    'ofceth:thusd',
    'thUSD',
    6,
    'eth:thusd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '33656cee-7e60-424c-930e-6525c6bcbeda',
    'ofceth:sthusd',
    'Staked thUSD',
    6,
    'eth:sthusd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'f284e63e-381b-48e0-9f7d-dfecebbb8b9e',
    'ofceth:cap',
    'Cap',
    18,
    'eth:cap' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '5f4cbbd9-7ced-4ef9-9499-9f8e1203e6e4',
    'ofceth:allo',
    'Allora',
    18,
    'eth:allo' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '4ca27260-c918-40c9-a8db-456748ee00e3',
    'ofceth:b2m',
    'Bit2Me',
    18,
    'eth:b2m' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'fdb99096-e2ef-4f9d-8c4d-bac239d0d44d',
    'ofceth:best',
    'Bitpanda Ecosystem Token',
    18,
    'eth:best' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'e0e92565-5a91-4c30-908f-4bfed228be1c',
    'ofceth:boson',
    'Boson Protocol',
    18,
    'eth:boson' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '606d285e-3db2-4751-87a9-6fe32b786443',
    'ofceth:justice',
    'AssangeDAO',
    18,
    'eth:justice' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'da1197d1-18ca-4e31-9a47-1b76824da25b',
    'ofceth:kan',
    'BitKan',
    18,
    'eth:kan' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '0cabf96f-edf1-4446-a105-22e701526fdb',
    'ofceth:plu',
    'Pluton',
    18,
    'eth:plu' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'ef627e15-5103-45b4-85c6-a4cf0a5c5c8a',
    'ofceth:pnk',
    'Kleros',
    18,
    'eth:pnk' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '475b65c8-3adc-487b-a03c-b34120802c82',
    'ofceth:suku',
    'Suku',
    18,
    'eth:suku' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '0a92edc3-8e12-4a59-b468-ad92af8dd446',
    'ofceth:velar',
    'Velar',
    18,
    'eth:velar' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '2fd0fd8c-cca6-4ab5-b631-ba4a7f94181d',
    'ofceth:trusd',
    'Tori trUSD',
    18,
    'eth:trusd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '6e0ed739-dfbb-4392-b965-4c498e7c1bf9',
    'ofceth:bsb',
    'Block Street',
    18,
    'eth:bsb' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'a391c3e2-062f-4c7f-b8c1-e3cd5e5a2cb5',
    'ofceth:portal',
    'Portal',
    18,
    'eth:portal' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'b439976c-0a40-4278-be3d-1af9b2a8ab93',
    'ofceth:edge',
    'edgeX',
    18,
    'eth:edge' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'e0793505-584c-4ed8-b447-b369b2dab856',
    'ofceth:swell',
    'Swell Network',
    18,
    'eth:swell' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '4b5af401-31aa-49d5-9e2a-8c85b2778451',
    'ofceth:based',
    'Based',
    18,
    'eth:based' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'c0b5974e-6277-4681-862b-d15c984b9a31',
    'ofceth:robo',
    'Fabric Protocol',
    18,
    'eth:robo' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'd0f76e66-4515-4b48-93bd-363c5d40925f',
    'ofceth:blend',
    'Fluent',
    18,
    'eth:blend' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '30b60616-6342-4512-a340-5c366abf9342',
    'ofceth:avl',
    'Avalon Labs',
    18,
    'eth:avl' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '736b38fd-28f5-4e21-bbf5-4213db7f85ce',
    'ofceth:zkp',
    'zkPass',
    18,
    'eth:zkp' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'c9244669-0d9c-4073-a30d-1cb85a814a6d',
    'ofceth:tria',
    'Tria',
    18,
    'eth:tria' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '25339358-c59d-451f-aa7f-3d6892da9754',
    'ofceth:corn',
    'Corn',
    18,
    'eth:corn' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '31575bfe-5bd5-4f37-9a9d-32b1761fd4c7',
    'ofceth:apex',
    'ApeX Protocol',
    18,
    'eth:apex' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'ae79108b-7cd4-4ca7-bc72-726b8da29a17',
    'ofceth:vooi',
    'VOOI',
    18,
    'eth:vooi' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '60f9275a-5403-431c-95ae-c29947bbaa2e',
    'ofceth:imu',
    'Immunefi',
    18,
    'eth:imu' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'aa692cc6-4578-442d-94bc-e7106e7a8489',
    'ofceth:brev',
    'Brevis',
    18,
    'eth:brev' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
];
