import type { UnderlyingAsset } from '../base';
import * as AccountCtors from '../ofc';
export const botOfcTokens = [
  AccountCtors.ofcerc20(
    '26f46d44-700d-4e32-8845-fb181e6d8027',
    'ofceth:gusdcq',
    'Galaxy USDC Quality',
    18,
    'eth:gusdcq' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '336f05ca-6548-495e-9c0b-8deba95ea56b',
    'ofceth:gusdtq',
    'Galaxy USDT Quality',
    18,
    'eth:gusdtq' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '0c881f11-064e-4e54-9fa6-55406e419819',
    'ofceth:gwethq',
    'Galaxy WETH Quality',
    18,
    'eth:gwethq' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'f8ffca6e-a6dc-4d14-90d8-500383cdbffe',
    'ofceth:acu',
    'Acurast',
    12,
    'eth:acu' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '1a446703-1f79-4212-8ee2-5338515708d3',
    'ofceth:obol',
    'Obol',
    18,
    'eth:obol' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '6b42cbcb-1eba-4c20-be8b-f94e878f5365',
    'ofceth:re',
    'Re Protocol',
    18,
    'eth:re' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '186594ec-8433-46db-9756-f071c172fa67',
    'ofceth:filqa',
    'Fidelity USD Digital Liquidity Fund-Acc',
    2,
    'eth:filqa' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'b28d8ff5-a32a-44db-b1b1-c3b9f9a949c3',
    'ofceth:filqd',
    'Fidelity USD Digital Liquidity Fund-Dist',
    2,
    'eth:filqd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'bc9074f8-e75b-4daf-9305-1c1d31127264',
    'ofceth:wylds',
    'Hastra wYLDS',
    6,
    'eth:wylds' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '4451adc0-9d86-4518-87bf-fcaaf8fa43e8',
    'ofceth:hprime',
    'Hastra PRIME',
    6,
    'eth:hprime' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '8cfa782a-c177-4501-9af6-84423eeb2017',
    'ofceth:bill',
    'Billions Network',
    18,
    'eth:bill' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '4b5a115f-534e-4cd7-befc-9e432b6fe3c4',
    'ofceth:frnt',
    'Frontier Stable Token',
    6,
    'eth:frnt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '4f06be6b-081c-45cd-8d13-77f88e735ebc',
    'ofceth:usdds',
    'Usdd Stablecoin',
    18,
    'eth:usdds' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'b8f267b6-9060-4ca8-ae30-11d77a665d88',
    'ofceth:lbtc',
    'Lombard Staked BTC',
    8,
    'eth:lbtc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'fec0468d-29fa-4dcf-af02-4e63d434c9ad',
    'ofceth:usdai',
    'USDai',
    18,
    'eth:usdai' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '2ff046d0-12bf-4e67-a3e9-b974e99566a5',
    'ofceth:susdai',
    'Staked USDai',
    18,
    'eth:susdai' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'e6c700dc-6313-44e0-b4e9-b482d734f1cb',
    'ofceth:nvprime',
    'Nuva Prime Vault',
    18,
    'eth:nvprime' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'b4472153-1f02-45aa-b1b3-9a5793b2a5ae',
    'ofceth:king',
    'King Protocol',
    18,
    'eth:king' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'c9ab646b-209b-418b-8086-7c9a6c078068',
    'ofceth:valt',
    'VALT Token',
    18,
    'eth:valt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '549fa391-e575-49fc-971d-1ba42b90019f',
    'ofceth:myrt',
    'MYR Stablecoin',
    6,
    'eth:myrt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'fce95d17-085b-40f5-90a2-6eacb619a112',
    'ofceth:sent',
    'Sentient',
    18,
    'eth:sent' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'e7fb9bbd-e72d-4863-9aad-a851ac00c7c5',
    'ofceth:thusd',
    'thUSD',
    6,
    'eth:thusd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '33656cee-7e60-424c-930e-6525c6bcbeda',
    'ofceth:sthusd',
    'Staked thUSD',
    6,
    'eth:sthusd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'f284e63e-381b-48e0-9f7d-dfecebbb8b9e',
    'ofceth:cap',
    'Cap',
    18,
    'eth:cap' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '5f4cbbd9-7ced-4ef9-9499-9f8e1203e6e4',
    'ofceth:allo',
    'Allora',
    18,
    'eth:allo' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
];
