import type { UnderlyingAsset } from '../base';
import * as AccountCtors from '../ofc';
export const botOfcTokens = [
  AccountCtors.ofcerc20(
    'f94875df-0a1e-4550-a75c-bad07f64f708',
    'ofceth:aethusdt',
    'Aave Ethereum USDT',
    8,
    'eth:aethusdt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '64a6001c-ffaa-444b-90ee-cd13a76e8cf1',
    'ofceth:aethusdc',
    'Aave Ethereum USDC',
    6,
    'eth:aethusdc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '30fe79ce-5f3e-483d-abaa-0d05f5577314',
    'ofceth:aethwbtc',
    'Aave Ethereum WBTC',
    8,
    'eth:aethwbtc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'ced14516-7d18-47a3-bd05-b8198b0bfde6',
    'ofceth:aethcbbtc',
    'Aave Ethereum cbBTC',
    8,
    'eth:aethcbbtc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'e1ecd4de-f19e-4da6-8c5d-f5fa238ec853',
    'ofceth:aethusde',
    'Aave Ethereum USDe',
    18,
    'eth:aethusde' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '073b057f-957f-4293-a148-dc5a47d77114',
    'ofceth:aethxaut',
    'Aave Ethereum XAUt',
    6,
    'eth:aethxaut' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '5b76e064-9595-4a71-9a6e-5f9ee6e219d9',
    'ofceth:aethaave',
    'Aave Ethereum AAVE',
    18,
    'eth:aethaave' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '15aaba6b-fd11-4269-9dae-b8770ee05fd4',
    'ofceth:aetheurc',
    'Aave Ethereum EURC',
    6,
    'eth:aetheurc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'a10d01a5-bf6c-4f1c-bb22-d4544d6372a5',
    'ofceth:aethusdg',
    'Aave Ethereum USDG',
    6,
    'eth:aethusdg' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '64d24c47-3ba1-413e-b3c9-7fabfe6ac168',
    'ofceth:aethpyusd',
    'Aave Ethereum PYUSD',
    6,
    'eth:aethpyusd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'b49e0d41-6484-4dbf-8045-6b3af6a43db5',
    'ofceth:aethcbeth',
    'Aave Ethereum cbETH',
    18,
    'eth:aethcbeth' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '40dc2325-61dd-4380-96bc-a79080b74427',
    'ofceth:spusdc',
    'Spark Savings USDC',
    6,
    'eth:spusdc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'c0c983a6-c9e4-42d1-b3c9-2675ea5efcba',
    'ofceth:spusdt',
    'Spark Savings USDT',
    6,
    'eth:spusdt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '2aa437e9-ba5a-410d-a36f-69928ebca520',
    'ofceth:speth',
    'Spark Savings ETH',
    18,
    'eth:speth' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '9f465093-00b1-41d5-8da7-722e1771a32f',
    'ofceth:sppyusd',
    'Spark Savings PYUSD',
    6,
    'eth:sppyusd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '62893048-f2c5-4d16-af1f-efc89c47af79',
    'ofceth:spwsteth',
    'Spark wstETH',
    18,
    'eth:spwsteth' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'e892c3af-06b7-43a8-835a-a47711d7c950',
    'ofceth:spweth',
    'Spark WETH',
    18,
    'eth:spweth' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '49516014-f31b-4e63-b62c-9c02381568bd',
    'ofceth:spwbtc',
    'Spark WBTC',
    8,
    'eth:spwbtc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '3d127a9e-d9ee-4a06-9698-ad82ad4cf932',
    'ofceth:spcbbtc',
    'Spark cbBTC',
    8,
    'eth:spcbbtc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'a1b7e927-b2da-401c-8251-8d20ea13a1dd',
    'ofceth:syrupusdc',
    'Syrup USDC',
    6,
    'eth:syrupusdc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '0d7440fc-e0a6-4824-9077-8381b38ee14b',
    'ofceth:syrupusdt',
    'Syrup USDT',
    6,
    'eth:syrupusdt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'ace458bb-b294-4d5a-834f-222641c707ec',
    'ofceth:sparkusdt',
    'Spark USDT',
    6,
    'eth:sparkusdt' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '8843cfb2-9646-45f9-aad8-27db8ad9da09',
    'ofceth:sparkpyusd',
    'Spark PYUSD',
    6,
    'eth:sparkpyusd' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    'a2b4b76d-cf2c-45b8-8f2c-783f7ca58dd5',
    'ofceth:sparkusdc',
    'Spark USDC',
    6,
    'eth:sparkusdc' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
  AccountCtors.ofcerc20(
    '696ac363-9a05-4708-8c80-59caae3ac6dc',
    'ofceth:aethwsteth',
    'Wrapped liquid staked Ether 2.0',
    18,
    'eth:aethwsteth' as unknown as UnderlyingAsset,
    undefined,
    undefined,
    undefined,
    undefined,
    undefined
  ),
];
