---
kind: pipeline
name: audit

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:lts
  commands:
  - node --version
  - npm --version

- name: install
  image: node:lts
  commands:
  - npm install

- name: audit
  image: node:lts
  commands:
  - npm audit

---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:lts
  commands:
  - node --version
  - npm --version

- name: lint
  image: node:lts
  commands:
  - "npx eslint 'src/**/*.js'"

---
kind: pipeline
name: unit tests (node:8)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:8
  commands:
  - node --version
  - npm --version

- name: install
  image: node:8
  commands:
  - npm install

- name: unit tests
  image: node:8
  commands:
  - npm run test-node
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password

- name: upload coverage
  image: node:8
  commands:
  - "npx nyc report --reporter=text-lcov > coverage.lcov"
  - "npx codecov -f coverage.lcov -t \"$CODECOV_TOKEN\" -F unit"
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: unit tests (node:9)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:9
  commands:
  - node --version
  - npm --version

- name: install
  image: node:9
  commands:
  - npm install

- name: unit tests
  image: node:9
  commands:
  - npm run test-node
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password

- name: upload coverage
  image: node:9
  commands:
  - "npx nyc report --reporter=text-lcov > coverage.lcov"
  - "npx codecov -f coverage.lcov -t \"$CODECOV_TOKEN\" -F unit"
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: unit tests (node:10)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:10
  commands:
  - node --version
  - npm --version

- name: install
  image: node:10
  commands:
  - npm install

- name: unit tests
  image: node:10
  commands:
  - npm run test-node
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password

- name: upload coverage
  image: node:10
  commands:
  - "npx nyc report --reporter=text-lcov > coverage.lcov"
  - "npx codecov -f coverage.lcov -t \"$CODECOV_TOKEN\" -F unit"
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: unit tests (node:11)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:11
  commands:
  - node --version
  - npm --version

- name: install
  image: node:11
  commands:
  - npm install

- name: unit tests
  image: node:11
  commands:
  - npm run test-node
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password

- name: upload coverage
  image: node:11
  commands:
  - "npx nyc report --reporter=text-lcov > coverage.lcov"
  - "npx codecov -f coverage.lcov -t \"$CODECOV_TOKEN\" -F unit"
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

---
kind: pipeline
name: integration tests (node:10)

platform:
  os: linux
  arch: amd64

steps:
- name: build information
  image: node:10
  commands:
  - node --version
  - npm --version
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

- name: install
  image: node:10
  commands:
  - npm install
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

- name: integration tests
  image: node:10
  commands:
  - npx nyc -- node_modules/.bin/mocha --timeout 20000 --reporter list --exit --recursive test/v2/integration
  environment:
    BITGOJS_TEST_PASSWORD:
      from_secret: password
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

- name: upload coverage
  image: node:10
  commands:
  - "npx nyc report --reporter=text-lcov > coverage.lcov"
  - "npx codecov -f coverage.lcov -t \"$CODECOV_TOKEN\" -F integration"
  environment:
    CODECOV_TOKEN:
      from_secret: codecov
  when:
    branch:
    - master
    - "rel/*"
    - prod/production

...
