// Re-export these for backwards compat
export {
  AddressGenerationError,
  AddressTypeChainMismatchError,
  ApiResponseError,
  BitGoJsError,
  BlockExplorerUnavailable,
  ErrorNoInputToRecover,
  EthereumLibraryUnavailableError,
  InvalidAddressDerivationPropertyError,
  InvalidAddressError,
  InvalidAddressVerificationObjectPropertyError,
  InvalidKeyPathError,
  InvalidMemoIdError,
  InvalidPaymentIdError,
  InvalidTransactionError,
  KeyRecoveryServiceError,
  MethodNotImplementedError,
  NodeEnvironmentError,
  P2shP2wshUnsupportedError,
  P2trUnsupportedError,
  P2wshUnsupportedError,
  StellarFederationUserNotFoundError,
  TlsConfigurationError,
  UnexpectedAddressError,
  UnsupportedAddressTypeError,
  UnsupportedCoinError,
  WalletRecoveryUnsupported,
} from '@bitgo/sdk-core';
