import * as t from 'io-ts';
import { httpRoute, httpRequest, optional } from '@api-ts/io-ts-http';
import { BitgoExpressError } from '../../schemas/error';

/**
 * Request parameters for consolidating unspents in a wallet (v2)
 */
export const ConsolidateUnspentsRequestParams = {
  /** A cryptocurrency or token ticker symbol */
  coin: t.string,
  /** The wallet ID */
  id: t.string,
} as const;

/**
 * Request body for consolidating unspents in a wallet (v2)
 *
 * This endpoint supports the full set of parameters available in the BitGo SDK
 * for advanced UTXO management. The consolidate operation takes multiple unspents and
 * combines them into fewer outputs to reduce the number of UTXOs in a wallet.
 */
export const ConsolidateUnspentsRequestBody = {
  /** Passphrase to decrypt the user key on the wallet */
  walletPassphrase: optional(t.string),
  /** Private key in string form, if walletPassphrase is not available */
  xprv: optional(t.string),
  /** Minimum value of unspents to use in base units (e.g. satoshis). Can be used to skip very small unspents when consolidating at higher fee rates. For doge, only string is allowed */
  minValue: optional(t.union([t.number, t.string])),
  /** Maximum value of unspents to use in base units (e.g. satoshis). Should be used to prevent larger unspents from being consolidated needlessly, and that some funds remain available for spending while the consolidation transactions are in flight. For doge, only string is allowed */
  maxValue: optional(t.union([t.number, t.string])),
  /** Minimum height of unspents on the block chain to use */
  minHeight: optional(t.number),
  /** Number of new unspents to make (not applicable for bulk consolidation) */
  numUnspentsToMake: optional(t.number),
  /** Block target for fee estimation */
  feeTxConfirmTarget: optional(t.number),
  /** Maximum number of unspents to use in the transaction */
  limit: optional(t.number),
  /** Minimum confirmation threshold for external inputs */
  minConfirms: optional(t.number),
  /** Flag for enforcing minConfirms for change inputs */
  enforceMinConfirmsForChange: optional(t.boolean),
  /** Custom fee rate (in base units) per kilobyte (or virtual kilobyte). For example, satoshis per kvByte */
  feeRate: optional(t.number),
  /** (BTC only) The maximum fee rate (in base units) per kilobyte (or virtual kilobyte). For example, satoshis per kvByte. The `maxFeeRate` limits the fee rate generated by both `feeMultiplier` and `numBlocks` */
  maxFeeRate: optional(t.number),
  /** Maximum relative portion that can be spent towards fees */
  maxFeePercentage: optional(t.number),
  /** Comment to attach to the transaction */
  comment: optional(t.string),
  /** One-time password for 2FA */
  otp: optional(t.string),
  /** address to use for generated outputs. Must be wallet address */
  targetAddress: optional(t.string),
  /** [UTXO only] Format of the returned transaction hex serialization. `legacy` for serialized transaction in custom bitcoinjs-lib format. `psbt` for BIP174 serialized transaction */
  txFormat: optional(t.union([t.literal('legacy'), t.literal('psbt'), t.literal('psbt-lite')])),
  /** Build multiple transactions at the same time. This enables you to increase the maximum number of unspents on the `limit` parameter up to 2,000. If true, you must pass the `txFormat` as `psbt` and you can't pass the `targetAddress` or `numUnspentsToMake` parameters */
  bulk: optional(t.boolean),
} as const;

/**
 * Single transaction response object
 */
const ConsolidateUnspentsSingleTxResponse = t.type({
  /** The status of the transaction ('accepted', 'signed', 'pendingApproval', or 'otp') */
  status: t.string,
  /** The transaction hex/serialized transaction */
  tx: t.string,
  /** The transaction hash/ID */
  hash: optional(t.string),
  /** Alternative field for transaction ID (some responses use this instead of hash) */
  txid: optional(t.string),
  /** The fee amount in base units (satoshis for BTC) */
  fee: optional(t.number),
  /** The fee rate in base units per kilobyte (satoshis/kB for BTC) */
  feeRate: optional(t.number),
  /** Whether the transaction is instant */
  instant: optional(t.boolean),
  /** The instant transaction ID (if applicable) */
  instantId: optional(t.string),
  /** Travel rule information */
  travelInfos: optional(t.unknown),
  /** BitGo fee information (if applicable) */
  bitgoFee: optional(t.unknown),
  /** Travel rule result (if applicable) */
  travelResult: optional(t.unknown),
});

/**
 * Response for consolidating unspents in a wallet (v2)
 *
 * Returns transaction details after the consolidation operation is built, signed, and sent.
 * When bulk=true, an array of transaction objects is returned; otherwise, a single transaction object is returned.
 */
export const ConsolidateUnspentsResponse = t.union([
  ConsolidateUnspentsSingleTxResponse,
  t.array(ConsolidateUnspentsSingleTxResponse),
]);

/**
 * Builds, signs, and sends a transaction to consolidate unspents all in 1 call. Consolidating unspents is only for UTXO-based assets.
 *
 * @operationId express.wallet.consolidateunspents
 * @tag Express
 */
export const PostConsolidateUnspents = httpRoute({
  path: '/api/v2/{coin}/wallet/{id}/consolidateunspents',
  method: 'POST',
  request: httpRequest({
    params: ConsolidateUnspentsRequestParams,
    body: ConsolidateUnspentsRequestBody,
  }),
  response: {
    /** Successfully consolidated unspents */
    200: ConsolidateUnspentsResponse,
    /** Invalid request or consolidation operation fails */
    400: BitgoExpressError,
  },
});
