import * as t from 'io-ts';
import { httpRoute, httpRequest } from '@api-ts/io-ts-http';
import { BitgoExpressError } from '../../schemas/error';
import { DecryptRequestBody } from '../v1/decrypt';

/**
 * Decrypt message
 *
 * Decrypt a ciphertext generated by encrypt route with provided password
 *
 * @operationId express.decrypt
 * @tag Express
 * @public
 */
export const PostV2Decrypt = httpRoute({
  path: '/api/v2/decrypt',
  method: 'POST',
  request: httpRequest({
    body: DecryptRequestBody,
  }),
  response: {
    200: t.type({
      decrypted: t.string,
    }),
    404: BitgoExpressError,
  },
});
