import * as t from 'io-ts';
import { Json, NonEmptyString } from 'io-ts-types';
import { httpRoute, httpRequest, optional } from '@api-ts/io-ts-http';
import { BitgoExpressError } from '../../schemas/error';

/**
 * Sign an arbitrary payload using an OFC trading account key.
 * POST /api/v2/ofc/signPayload
 */
export const OfcSignPayloadBody = {
  /** The ID of the wallet to use for signing. */
  walletId: NonEmptyString,
  /** The JSON payload to sign. */
  payload: Json,
  /** The passphrase for the wallet (optional). */
  walletPassphrase: optional(t.string),
};

export const OfcSignPayloadResponse200 = t.type({
  /** The canonical string form of the JSON payload that was signed. */
  payload: t.string,
  /** Hex-encoded signature generated by the trading account key. */
  signature: t.string,
});

/**
 * Response for signPayload request.
 */
export const OfcSignPayloadResponse = {
  /** The canonical string form of the JSON payload that was signed and the hex-encoded signature generated by the trading account key. */
  200: OfcSignPayloadResponse200,
  /** BitGo Express error payload. */
  400: BitgoExpressError,
} as const;

/**
 * Request body for signing an arbitrary payload with an OFC wallet key.
 *
 * @operationId express.ofc.signPayload
 */
export const PostOfcSignPayload = httpRoute({
  path: '/api/v2/ofc/signPayload',
  method: 'POST',
  request: httpRequest({ body: OfcSignPayloadBody }),
  response: OfcSignPayloadResponse,
});

export type PostOfcSignPayload = typeof PostOfcSignPayload;
