import * as t from 'io-ts';
import { Json, NonEmptyString } from 'io-ts-types';
import { httpRoute, httpRequest, optional } from '@api-ts/io-ts-http';
import { BitgoExpressError } from '../../schemas/error';
import { JsonFromStringifiedJson } from '../../schemas/jsonFromStringifiedJson';

/**
 * Sign an arbitrary payload using an OFC trading account key.
 */
export const OfcSignPayloadBody = {
  /** The ID of the OFC wallet to sign the payload with. */
  walletId: NonEmptyString,
  /** The payload to sign. The input can either be a stringified JSON, or a JSON object. */
  payload: t.union([Json, JsonFromStringifiedJson]),
  /** The passphrase to decrypt the user key. */
  walletPassphrase: optional(t.string),
} as const;

export const OfcSignPayloadResponse200 = t.type({
  /** The string form of the JSON payload that was signed. */
  payload: t.string,
  /** Hex-encoded signature generated by the trading account key. */
  signature: t.string,
});

/**
 * Response for signing an arbitrary payload with an OFC wallet key.
 */
export const OfcSignPayloadResponse = {
  /** Signed payload and signature */
  200: OfcSignPayloadResponse200,
  /** BitGo Express error payload. */
  400: BitgoExpressError,
} as const;

/** Sign payload with an OFC wallet key.
 * Signs an arbitrary payload with an OFC wallet key.
 *
 * @operationId express.ofc.signPayload
 * @tag express
 */
export const PostOfcSignPayload = httpRoute({
  path: '/api/v2/ofc/signPayload',
  method: 'POST',
  request: httpRequest({ body: OfcSignPayloadBody }),
  response: OfcSignPayloadResponse,
});
