import * as t from 'io-ts';
import { DateFromISOString } from 'io-ts-types';
import { httpRoute, httpRequest, optional } from '@api-ts/io-ts-http';
import { TransactionRequest as TxRequestResponse } from '@bitgo/public-types';
import { BitgoExpressError } from '../../schemas/error';

/**
 * Request parameters for sending to multiple recipients (v2)
 */
export const SendManyRequestParams = {
  /** A cryptocurrency or token ticker symbol. */
  coin: t.string,
  /** The wallet ID. */
  id: t.string,
} as const;

/**
 * EIP-1559 fee parameters for Ethereum transactions
 *
 * Accepts:
 * - Empty object {} - triggers automatic fee estimation (backward compatible)
 * - Object with both maxFeePerGas AND maxPriorityFeePerGas - uses provided values
 *
 * Note: Partial objects (only one field) pass validation but backend handles them
 */
export const EIP1559Params = t.partial({
  /** Maximum priority fee per gas (in wei) */
  maxPriorityFeePerGas: t.union([t.number, t.string]),
  /** Maximum fee per gas (in wei) */
  maxFeePerGas: t.union([t.number, t.string]),
});

/**
 * Memo object for chains that support memos (e.g., Stellar, XRP)
 * When memo object is present, both fields are REQUIRED
 */
export const MemoParams = t.type({
  /** Memo value - REQUIRED */
  value: t.string,
  /** Memo type - REQUIRED */
  type: t.string,
});

/**
 * Token transfer recipient parameters
 * tokenType and tokenQuantity are REQUIRED when this object is present
 */
const TokenTransferRecipientParams = t.intersection([
  t.type({
    /** Type of token (e.g., 'ERC20', 'ERC721', 'ERC1155', 'NATIVE') - REQUIRED */
    tokenType: t.string,
    /** Quantity of tokens to transfer (as string) - REQUIRED */
    tokenQuantity: t.string,
  }),
  t.partial({
    /** Token contract address (for ERC20, ERC721, etc.) - OPTIONAL */
    tokenContractAddress: t.string,
    /** Token name - OPTIONAL */
    tokenName: t.string,
    /** Token ID (for NFTs - ERC721, ERC1155) - OPTIONAL */
    tokenId: t.string,
    /** Decimal places for the token - OPTIONAL */
    decimalPlaces: t.number,
  }),
]);

/**
 * Recipient object for sendMany transactions
 */
const RecipientParams = t.type({
  /** Recipient address */
  address: t.string,
  /** Amount to send (in base units, e.g., satoshis for BTC, wei for ETH) */
  amount: t.union([t.number, t.string]),
});

const RecipientParamsOptional = t.partial({
  /** Fee limit for this specific recipient (e.g., for Tron TRC20 tokens) */
  feeLimit: t.string,
  /** Data field for this recipient (can be hex string or token transfer params) */
  data: t.union([t.string, TokenTransferRecipientParams]),
  /** Token name for this specific recipient */
  tokenName: t.string,
  /** Token data for this specific recipient */
  tokenData: TokenTransferRecipientParams,
});

/**
 * Complete recipient object combining required and optional fields
 */
const Recipient = t.intersection([RecipientParams, RecipientParamsOptional]);

/**
 * Token enablement configuration
 * name is REQUIRED when this object is present
 */
export const TokenEnablement = t.intersection([
  t.type({
    /** Token name - REQUIRED */
    name: t.string,
  }),
  t.partial({
    /** Token address (some chains like Solana require tokens to be enabled for specific address) - OPTIONAL */
    address: t.string,
  }),
]);

/**
 * Request body for sending to multiple recipients (v2)
 *
 * This endpoint supports the full set of parameters available in the BitGo SDK
 * for building, signing, and sending transactions to multiple recipients.
 */
export const SendManyRequestBody = {
  /** A list of recipient addresses and amounts. Must be present but empty for CPFP transactions. */
  recipients: optional(t.array(Recipient)),

  /** Passphrase to decrypt the user key on the wallet. Required if External Signer is not used to sign the transactions. */
  walletPassphrase: optional(t.string),

  /** The extended private key (alternative to walletPassphrase) */
  xprv: optional(t.string),

  /** The un-encrypted user private key in string form. If the key is a JSON object it must be stringified. Required if `walletPassphrase` is not available or encrypted private key is not stored by BitGo. */
  prv: optional(t.string),

  /**
   * (BTC only) The number of blocks required to confirm a transaction. You can use `numBlocks` to estimate the fee
   * rate by targeting confirmation within a given number of blocks. If both `feeRate` and `numBlocks` are absent,
   * the transaction defaults to 2 blocks for confirmation.
   *
   * Note: The `maxFeeRate` limits the fee rate generated by `numBlocks`.
   */
  numBlocks: optional(t.number),

  /**
   * Custom fee rate (in base units) per kilobyte (or virtual kilobyte). For example, satoshis per kvByte.
   *
   * If the `feeRate` is less than the minimum required network fee, then the minimum fee applies. For example,
   * 1000 sat/kvByte, a flat 1000 microAlgos, or a flat 10 drops of xrp. For XRP, the actual fee is usually
   * 4.5 times the open ledger fee.
   *
   * Note: The `feeRate` overrides the `maxFeeRate` and `minFeeRate`.
   */
  feeRate: optional(t.number),

  /**
   * (UTXO only) Custom multiplier to the `feeRate`. The resulting fee rate is limited by the `maxFeeRate`.
   * For replace-by-fee (RBF) transactions (that include `rbfTxIds`), the `feeMultiplier` must be greater than 1,
   * since it's an absolute fee multiplier to the transaction being replaced.
   *
   * Note: The `maxFeeRate` limits the fee rate generated by `feeMultiplier`.
   */
  feeMultiplier: optional(t.number),

  /**
   * (BTC only) The maximum fee rate (in base units) per kilobyte (or virtual kilobyte). For example, satoshis per kvByte.
   * The `maxFeeRate` limits the fee rate generated by both `feeMultiplier` and `numBlocks`.
   *
   * Note: The `feeRate` overrides the `maxFeeRate`.
   */
  maxFeeRate: optional(t.number),

  /** The unspent selection for the transaction will only consider unspents with at least this many confirmations to be used as inputs. Does not apply to change outputs unless used in combination with `enforceMinConfirmsForChange`. */
  minConfirms: optional(t.number),

  /** Defaults to false. When set to true, will enforce minConfirms for change outputs. */
  enforceMinConfirmsForChange: optional(t.boolean),

  /**
   * Defaults to 1000. Specifies the minimum count of good-sized unspents to maintain in the wallet.
   * Change splitting ceases when the wallet has `targetWalletUnspents` good-sized unspents.
   *
   * Note: Wallets that continuously send a high count of transactions will automatically split large change amounts
   * into multiple good-sized change outputs while they have fewer than `targetWalletUnspents` good-sized unspents
   * in their unspent pool. Breaking up large unspents helps to reduce the amount of unconfirmed funds in flight in
   * future transactions, and helps to avoid long chains of unconfirmed transactions. This is especially useful for
   * newly funded wallets or recently refilled send-only wallets.
   */
  targetWalletUnspents: optional(t.number),

  /** Message to attach to the transaction */
  message: optional(t.string),

  /** Ignore unspents smaller than this amount of base units (e.g. satoshis). For doge, only string is allowed. */
  minValue: optional(t.union([t.number, t.string])),

  /** Ignore unspents larger than this amount of base units (e.g. satoshis). For doge, only string is allowed. */
  maxValue: optional(t.union([t.number, t.string])),

  /**
   * A `sequenceId` is a unique and arbitrary wallet identifier applied to transfers and transactions at creation.
   * It is optional but highly recommended. With a `sequenceId` you can easily reference transfers and transactions—
   * for example, to safely retry sending. Because the system only confirms one send request per `sequenceId`
   * (and fails all subsequent attempts), you can retry sending without the risk of double spending.
   * The `sequenceId` is only visible to users on the wallet and is not shared publicly.
   */
  sequenceId: optional(t.string),

  /** (XRP only) Absolute max ledger the transaction should be accepted in, whereafter it will be rejected. */
  lastLedgerSequence: optional(t.number),

  /** (XRP only) Relative ledger height (in relation to the current ledger) that the transaction should be accepted in, whereafter it will be rejected. */
  ledgerSequenceDelta: optional(t.number),

  /** Custom gas price to be used for sending the transaction. Only for ETH and ERC20 tokens. */
  gasPrice: optional(t.number),

  /** Defaults to false. Set `true` to disable automatic change splitting. Also see: `targetWalletUnspents` */
  noSplitChange: optional(t.boolean),

  /** Used to explicitly specify the unspents to be used in the input set in the transaction. Each unspent should be in the form `prevTxId:nOutput`. */
  unspents: optional(t.array(t.string)),

  /** Optional metadata (only persisted in BitGo) to be applied to the transaction. Use this to add transaction-specific information such as the transaction's purpose or another identifier that you want to reference later. The value is shown in the UI in the transfer listing page. (length ≤ 256) */
  comment: optional(t.string),

  /** Two factor auth code to enable sending the transaction. Not necessary if using a long lived access token within the spending limit. */
  otp: optional(t.string),

  /** Specifies a custom destination address for the transaction's change output(s) (length ≤ 500) */
  changeAddress: optional(t.string),

  /** If true, allows using an external change address */
  allowExternalChangeAddress: optional(t.boolean),

  /** (DASH only) Specifies whether or not to use Dash's "InstantSend" feature when sending a transaction. */
  instant: optional(t.boolean),

  /** Extra transaction information for CSPR, EOS, HBAR, RUNE, STX, TON, XLM, and XRP. Required for XLM transactions. Note: For XRP this is the destination tag (DT). For CSPR this is the transfer ID. */
  memo: optional(MemoParams),

  /** Transfer ID for tracking purposes */
  transferId: optional(t.number),

  /** EIP-1559 fee parameters for Ethereum transactions */
  eip1559: optional(EIP1559Params),

  /** Custom gas limit to be used for sending the transaction. Only for ETH and ERC20 tokens. */
  gasLimit: optional(t.number),

  /** Token name, defined in the BitGoJS Statics package. */
  tokenName: optional(t.string),

  /**
   * Required for transactions from MPC wallets. "acceleration" speeds up transactions with a certain nonce by
   * adjusting the gas setting. "accountSet" is for XRP AccountSet transactions. "consolidate" combines multiple
   * UTXO inputs into fewer outputs. "enabletoken" is for SOL. "fanout" splits UTXO inputs into many smaller outputs
   * (UTXO coins only). "stakingLock" and "stakingUnlock" are for Stacks delegations. "transfer" is for native-asset
   * transfers. "trustline" is for Stellar trustline transactions.
   * Possible types include: [acceleration, accountSet, consolidate, enabletoken, fanout, stakingLock, stakingUnlock,
   * transfer, transfertoken, trustline].
   *
   * For AVAX, possible types include: `addValidator`, `export`, and `import`.
   * For XRP, possible types include: `payment` and `accountSet`. The default is `payment`.
   * For STX, type is required.
   */
  type: optional(t.string),

  /** Custodian transaction ID (for institutional custody integrations) */
  custodianTransactionId: optional(t.string),

  /** (ETH, AVAXC and POLYGON) Set to true if funds to destination need to come from single sig address. */
  hop: optional(t.boolean),

  /** @deprecated Use `changeAddressType` instead. The type of address to create for change. One of `p2sh`, `p2shP2wsh`, `p2wsh`, or `p2tr`. */
  addressType: optional(t.string),

  /** The address type for the change address. One of `p2sh`, `p2shP2wsh`, `p2wsh`, `p2tr` or `p2trMusig2`. */
  changeAddressType: optional(t.string),

  /** [UTXO only] Format of the returned transaction hex serialization. `legacy` for serialized transaction in custom bitcoinjs-lib format. `psbt` for BIP174 serialized transaction. Defaults to `legacy`. */
  txFormat: optional(t.union([t.literal('legacy'), t.literal('psbt'), t.literal('psbt-lite')])),

  /** If set to false, sweep all funds including required minimums (e.g., DOT requires 1 DOT minimum) */
  keepAlive: optional(t.boolean),

  /** NFT collection ID (for NFT transfers) */
  nftCollectionId: optional(t.string),

  /** NFT ID (for NFT transfers) */
  nftId: optional(t.string),

  /** (DOT only) A nonce ID is a number used to protect private communications by preventing replay attacks. This is an advanced option where users can manually input a new nonce value in order to correct or fill in a missing nonce ID value. */
  nonce: optional(t.string),

  /** If true, only preview the transaction without sending */
  preview: optional(t.boolean),

  /** Receive address (for specific coins like ADA) */
  receiveAddress: optional(t.string),

  /** [UTXO only] An array of messages that you sign with the wallet keys using the BIP322 format. If passed, the `recipients` array must be empty. */
  messages: optional(
    t.array(
      t.type({
        address: t.string,
        message: t.string,
      })
    )
  ),

  /** The receive address from which funds will be withdrawn (supported for specific coins like ADA) */
  senderAddress: optional(t.string),

  /** The wallet ID of the sender wallet when different from current wallet (for BTC unstaking) */
  senderWalletId: optional(t.string),

  /** Close remainder to address (for specific blockchain protocols like Algorand) */
  closeRemainderTo: optional(t.string),

  /** Non-participation flag (for governance/staking protocols like Algorand) */
  nonParticipation: optional(t.boolean),

  /** Optional block this transaction is valid from. */
  validFromBlock: optional(t.number),

  /** Optional block this transaction is valid until. */
  validToBlock: optional(t.number),

  /** Optional parameter for UTXO coins to automatically reserve the unspents that are used in the build. Useful for Cold wallets. If using, must set `expireTime`. */
  reservation: optional(
    t.partial({
      expireTime: t.string,
      pendingApprovalId: t.string,
    })
  ),

  /** Enable offline transaction verification */
  offlineVerification: optional(t.boolean),

  /** Wallet contract address (for smart contract wallets) */
  walletContractAddress: optional(t.string),

  /** IDF (Identity Framework) signed timestamp */
  idfSignedTimestamp: optional(t.string),

  /** IDF user ID */
  idfUserId: optional(t.string),

  /** IDF version number */
  idfVersion: optional(t.number),

  /** Array of tokens to enable on the wallet */
  enableTokens: optional(t.array(TokenEnablement)),

  /** Low fee transaction ID (for CPFP - Child Pays For Parent) */
  lowFeeTxid: optional(t.string),

  /** Flag indicating if this is a TSS transaction */
  isTss: optional(t.boolean),

  /** API version to use for the transaction */
  apiVersion: optional(t.string),

  /** Custom Solana instructions to include in the transaction */
  solInstructions: optional(
    t.array(
      t.type({
        programId: t.string,
        keys: t.array(
          t.type({
            pubkey: t.string,
            isSigner: t.boolean,
            isWritable: t.boolean,
          })
        ),
        data: t.string,
      })
    )
  ),

  /** Solana versioned transaction data for building transactions with Address Lookup Tables */
  solVersionedTransactionData: optional(
    t.partial({
      versionedInstructions: t.array(
        t.type({
          programIdIndex: t.number,
          accountKeyIndexes: t.array(t.number),
          data: t.string,
        })
      ),
      addressLookupTables: t.array(
        t.type({
          accountKey: t.string,
          writableIndexes: t.array(t.number),
          readonlyIndexes: t.array(t.number),
        })
      ),
      staticAccountKeys: t.array(t.string),
      messageHeader: t.type({
        numRequiredSignatures: t.number,
        numReadonlySignedAccounts: t.number,
        numReadonlyUnsignedAccounts: t.number,
      }),
      recentBlockhash: t.string,
    })
  ),

  /** Custom transaction parameters for Aptos entry function calls */
  aptosCustomTransactionParams: optional(
    t.intersection([
      t.type({
        /** Module name - REQUIRED */
        moduleName: t.string,
        /** Function name - REQUIRED */
        functionName: t.string,
      }),
      t.partial({
        /** Type arguments - OPTIONAL */
        typeArguments: t.array(t.string),
        /** Function arguments - OPTIONAL */
        functionArguments: t.array(t.any),
        /** ABI - OPTIONAL */
        abi: t.any,
      }),
    ])
  ),

  /** Array of public keys for signing */
  pubs: optional(t.array(t.string)),

  /** Transaction request ID (for TSS wallets) */
  txRequestId: optional(t.string),

  /** Co-signer public key */
  cosignerPub: optional(t.string),

  /** Flag indicating if this is the last signature */
  isLastSignature: optional(t.boolean),

  /** Pre-built transaction object */
  txPrebuild: optional(t.any),

  /** Multisig type version (e.g., 'MPCv2') */
  multisigTypeVersion: optional(t.literal('MPCv2')),

  /** Pre-built transaction (hex string or serialized object) */
  prebuildTx: optional(t.union([t.string, t.any])),

  /** Verification options for the transaction */
  verification: optional(t.any),

  /** Transaction verification parameters (used for verifying transaction before signing) */
  verifyTxParams: optional(
    t.intersection([
      t.type({
        /** Transaction parameters to verify - REQUIRED when verifyTxParams is present */
        txParams: t.partial({
          /** Recipients for verification */
          recipients: t.array(
            t.intersection([
              t.type({
                /** Recipient address */
                address: t.string,
                /** Amount to send */
                amount: t.union([t.string, t.number]),
              }),
              t.partial({
                /** Token name */
                tokenName: t.string,
                /** Memo */
                memo: t.string,
              }),
            ])
          ),
          /** Wallet passphrase */
          walletPassphrase: t.string,
          /** Transaction type */
          type: t.string,
          /** Memo for verification */
          memo: MemoParams,
          /** Tokens to enable */
          enableTokens: t.array(TokenEnablement),
        }),
      }),
      t.partial({
        /** Verification options - OPTIONAL */
        verification: t.any,
      }),
    ])
  ),
} as const;

/**
 * Entry in a transfer (input or output)
 */
const TransferEntry = t.intersection([
  t.type({
    /** Address associated with this entry - REQUIRED */
    address: t.string,
  }),
  t.partial({
    /** Label for the address - OPTIONAL */
    label: t.string,
    /** Whether this entry failed - OPTIONAL */
    failed: t.boolean,
    /** Whether this is a change output - OPTIONAL */
    isChange: t.boolean,
    /** Whether this is a fee entry - OPTIONAL */
    isFee: t.boolean,
    /** Whether this is an internal transfer - OPTIONAL */
    isInternal: t.boolean,
    /** Whether this is a PayGo entry - OPTIONAL */
    isPayGo: t.boolean,
    /** Memo associated with this entry - OPTIONAL */
    memo: t.string,
    /** Reward address (for staking) - OPTIONAL */
    rewardAddress: t.string,
    /** Entry subtype - OPTIONAL */
    subtype: t.string,
    /** Token name - OPTIONAL */
    token: t.string,
    /** Token contract hash - OPTIONAL */
    tokenContractHash: t.string,
    /** Value in base units (number) - OPTIONAL */
    value: t.number,
    /** Value as string - OPTIONAL */
    valueString: t.string,
    /** Wallet ID - OPTIONAL */
    wallet: t.string,
    /** Backing fee as string - OPTIONAL */
    backingFeeString: t.string,
    /** Entry type - OPTIONAL */
    type: t.string,
    /** NFT ID - OPTIONAL */
    nftId: t.string,
    /** NFT symbol - OPTIONAL */
    nftSymbol: t.string,
    /** Associated native coin address - OPTIONAL */
    associatedNativeCoinAddress: t.string,
  }),
]);

/**
 * History item in transfer history
 */
const TransferHistory = t.intersection([
  t.type({
    /** Action performed (e.g., 'created', 'signed', 'confirmed') - REQUIRED */
    action: t.string,
    /** Date of the action - REQUIRED */
    date: DateFromISOString,
  }),
  t.partial({
    /** Comment for this history item - OPTIONAL */
    comment: t.string,
    /** Transfer ID (for replaced transfers) - OPTIONAL */
    transferId: t.string,
    /** Transaction ID - OPTIONAL */
    txid: t.string,
    /** User who performed the action - OPTIONAL */
    user: t.string,
    /** Malformed transfer data - OPTIONAL */
    malformedTransfer: t.unknown,
  }),
]);

/**
 * Transfer object returned by sendMany - simplified with optional fields
 */
export const Transfer = t.type({
  /** Coin identifier - REQUIRED */
  coin: t.string,
  /** Transfer ID - REQUIRED */
  id: t.string,
  /** Wallet ID - REQUIRED */
  wallet: t.string,
  /** Enterprise ID - OPTIONAL */
  enterprise: optional(t.string),
  /** Transaction ID - REQUIRED */
  txid: t.string,
  /** Transaction ID type - OPTIONAL */
  txidType: optional(t.string),
  /** Block height - REQUIRED */
  height: t.number,
  /** Height ID - OPTIONAL */
  heightId: optional(t.string),
  /** Transfer date - REQUIRED */
  date: DateFromISOString,
  /** Number of confirmations - REQUIRED */
  confirmations: t.number,
  /** Transfer type ('send' or 'receive') - REQUIRED */
  type: t.string,
  /** Value (number) - OPTIONAL */
  value: optional(t.number),
  /** Value as string - REQUIRED */
  valueString: t.string,
  /** Intended value string - OPTIONAL */
  intendedValueString: optional(t.string),
  /** Base value (in base currency) - OPTIONAL */
  baseValue: optional(t.number),
  /** Base value as string - OPTIONAL */
  baseValueString: optional(t.string),
  /** Base value without fees - OPTIONAL */
  baseValueWithoutFees: optional(t.number),
  /** Base value without fees as string - OPTIONAL */
  baseValueWithoutFeesString: optional(t.string),
  /** Fee as string - OPTIONAL */
  feeString: optional(t.string),
  /** PayGo fee - OPTIONAL */
  payGoFee: optional(t.number),
  /** PayGo fee as string - OPTIONAL */
  payGoFeeString: optional(t.string),
  /** USD value of the transfer in dollars - OPTIONAL */
  usd: optional(t.number),
  /** USD exchange rate used for conversion - OPTIONAL */
  usdRate: optional(t.number),
  /** Transfer state (e.g., 'signed', 'confirmed', 'rejected') - REQUIRED */
  state: t.string,
  /** Tags - OPTIONAL */
  tags: optional(t.array(t.string)),
  /** Transfer history - REQUIRED */
  history: t.array(TransferHistory),
  /** Transfer comment - OPTIONAL */
  comment: optional(t.string),
  /** Virtual size (for Bitcoin) - OPTIONAL */
  vSize: optional(t.number),
  /** Coin-specific data (format varies by blockchain) - OPTIONAL */
  coinSpecific: optional(t.any),
  /** Sequence ID - OPTIONAL */
  sequenceId: optional(t.string),
  /** Array of entries (inputs/outputs) - OPTIONAL */
  entries: optional(t.array(TransferEntry)),
  /** Users notified flag - OPTIONAL */
  usersNotified: optional(t.boolean),
  /** Label (stored in DB, not returned in API response) - OPTIONAL */
  label: optional(t.string),
  /** Transfer IDs that this transfer replaces - OPTIONAL */
  replaces: optional(t.array(t.string)),
  /** Transfer ID that replaced this transfer - OPTIONAL */
  replacedBy: optional(t.array(t.string)),
});

/**
 * Resolver object for pending approval actions - simplified with optional fields
 * Represents a user who has resolved/approved a pending approval action
 */
const Resolver = t.type({
  /** User who resolved the action - REQUIRED */
  user: t.string,
  /** Date when the action was resolved - REQUIRED */
  date: DateFromISOString,
  /** Type of resolution (e.g., 'approved', 'rejected') - REQUIRED */
  resolutionType: t.string,
  /** Signatures provided during resolution - REQUIRED */
  signatures: t.array(t.string),
  /** Link to video verification (if applicable) - OPTIONAL */
  videoLink: optional(t.string),
  /** Video approver ID (if video verification was used) - OPTIONAL */
  videoApprover: optional(t.string),
  /** Video verification exception information - OPTIONAL */
  videoException: optional(t.string),
});

/**
 * Pending approval information - simplified with optional fields
 */
const PendingApprovalInfo = t.type({
  /** Type of pending approval - OPTIONAL */
  type: optional(t.string),
  /** Transaction request details - OPTIONAL */
  transactionRequest: optional(
    t.type({
      /** Build parameters - OPTIONAL */
      buildParams: optional(t.unknown),
      /** Coin-specific data - OPTIONAL */
      coinSpecific: optional(t.unknown),
      /** Comment - OPTIONAL */
      comment: optional(t.string),
      /** Fee - OPTIONAL */
      fee: optional(t.unknown),
      /** Whether transaction is unsigned - OPTIONAL */
      isUnsigned: optional(t.boolean),
      /** Recipients - OPTIONAL */
      recipients: optional(
        t.array(
          t.partial({
            /** Recipient address - OPTIONAL */
            address: t.string,
            /** Amount to send - OPTIONAL */
            amount: t.unknown,
            /** Data field - OPTIONAL */
            data: t.string,
          })
        )
      ),
      /** Requested amount - OPTIONAL */
      requestedAmount: optional(t.unknown),
      /** Source wallet ID - OPTIONAL */
      sourceWallet: optional(t.string),
      /** Triggered policy - OPTIONAL */
      triggeredPolicy: optional(t.unknown),
      /** Valid transaction - OPTIONAL */
      validTransaction: optional(t.string),
      /** Valid transaction hash - OPTIONAL */
      validTransactionHash: optional(t.string),
    })
  ),
});

/**
 * Pending approval object - simplified with optional fields to reduce type depth
 */
export const PendingApproval = t.type({
  /** Pending approval ID - OPTIONAL */
  id: optional(t.string),
  /** Coin type - OPTIONAL */
  coin: optional(t.string),
  /** Wallet ID (if wallet-level approval) - OPTIONAL */
  wallet: optional(t.string),
  /** Enterprise ID (if enterprise-level approval) - OPTIONAL */
  enterprise: optional(t.string),
  /** Organization ID - OPTIONAL */
  organization: optional(t.string),
  /** User who created the pending approval - OPTIONAL */
  creator: optional(t.string),
  /** Create date - OPTIONAL */
  createDate: optional(DateFromISOString),
  /** Pending approval information - OPTIONAL */
  info: optional(PendingApprovalInfo),
  /** State of the pending approval - OPTIONAL */
  state: optional(t.string),
  /** Scope of the pending approval - OPTIONAL */
  scope: optional(t.string),
  /** User IDs involved - OPTIONAL */
  userIds: optional(t.array(t.string)),
  /** Number of approvals required - OPTIONAL */
  approvalsRequired: optional(t.number),
  /** Wallet label - OPTIONAL */
  walletLabel: optional(t.string),
  /** Resolvers who have acted - OPTIONAL */
  resolvers: optional(t.array(Resolver)),
});

/**
 * Unified Response Codec for both 200 and 202 status codes
 * Split into smaller parts to avoid TypeScript maximum length error
 *
 * Covers all 5 response paths (see SENDMANY_RESPONSE_FLOWCHART.md):
 * - Path 1A: TSS Full API (Pending) → 200 with { pendingApproval, txRequest }
 * - Path 1B: TSS Full API (Success) → 200 or 202 with { transfer, txRequest, status, ... }
 * - Path 1C: TSS Lite API → 200 with TxRequest object
 * - Path 2: Custodial → 200 with { error?, pendingApprovals? }
 * - Path 3: Non-Custodial → 200 or 202 with { status, transfer?, ... }
 *
 * All fields are optional to accommodate different wallet types and scenarios.
 * The HTTP status code (200 vs 202) conveys the semantic difference.
 */

// Basic transaction fields
const SendManyResponseBasic = t.type({
  /** Transfer details - varies by coin and wallet type */
  transfer: optional(Transfer),
  /** Array of transfers (includes main transfer + optional fee transfer) */
  transfers: optional(t.array(Transfer)),
  /** Transaction status (e.g., 'signed', 'accepted', 'pendingApproval') */
  status: optional(t.string),
  /** Transaction hex */
  tx: optional(t.string),
  /** Transaction ID/hash */
  txid: optional(t.string),
});

// Complex type fields (using t.unknown to avoid TypeScript serialization limits)
const SendManyTxRequestResponse = t.type({
  /** Transaction request object - used in TSS wallets */
  txRequest: optional(TxRequestResponse),
});

const SendManyPendingApprovalResponse = t.type({
  /** Pending approval object - used when approval is pending */
  pendingApproval: optional(PendingApproval),
});

// Combined response codec
export const SendManyResponse = t.intersection([
  SendManyResponseBasic,
  SendManyTxRequestResponse,
  SendManyPendingApprovalResponse,
]);

/**
 * Send coins or tokens to one or more recipients. You can use this endpoint to schedule outgoing transactions in bulk, lowering your aggregate amount of blockchain fees.
 *
 * Works with both multisignature and MPC wallets. Also supports external-signer mode.
 *
 * Works with most BitGo-supported assets, but currently unavailable for: ALGO, ARBETH, AVAXC, CELO, CELO:CUSD, CSPR, DOT, EOS, HTETH:BGERCH, NEAR, OPETH, STX, TON, TRX, TRX:USDC, XLM, XRP, XTZ
 *
 * @operationId express.v2.wallet.sendmany
 * @tag Express
 */
export const PostSendMany = httpRoute({
  path: '/api/v2/{coin}/wallet/{id}/sendmany',
  method: 'POST',
  request: httpRequest({
    params: SendManyRequestParams,
    body: SendManyRequestBody,
  }),
  response: {
    /** Successfully sent transaction */
    200: SendManyResponse,
    /** Transaction requires approval (same structure as 200) */
    202: SendManyResponse,
    /** Invalid request or send operation fails */
    400: BitgoExpressError,
  },
});
