import * as t from 'io-ts';
import { httpRoute, httpRequest, optional, type HttpRoute } from '@api-ts/io-ts-http';
import { BitgoExpressError } from '../../schemas/error';
import { SendManyResponse, EIP1559Params, MemoParams, TokenEnablement } from './sendmany';

/**
 * Request parameters for sending to a single recipient (v2)
 */
export const SendCoinsRequestParams = {
  /** A cryptocurrency or token ticker symbol. (e.g., 'btc', 'tbtc', 'eth', 'teth') */
  coin: t.string,
  /** The wallet ID. */
  id: t.string,
} as const;

/**
 * Request body for sending to a single recipient (v2)
 *
 * This endpoint is a convenience wrapper around sendMany that accepts a single
 * address and amount instead of a recipients array. It supports the full set of
 * parameters available in sendMany.
 *
 * Internally, wallet.send() converts the address and amount into a recipients array
 * and calls wallet.sendMany(), so the response structure is identical.
 */
export const SendCoinsRequestBody = {
  /** Destination address (length ≤ 500) */
  address: t.string,

  /** Amount in base units (e.g. satoshi, wei, drops, stroops). For doge, only string is allowed. */
  amount: t.union([t.number, t.string]),

  /** (ETH only) Optional data to pass to the transaction */
  data: optional(t.string),

  /** Fee limit for this transaction (e.g., for Tron TRC20 tokens) */
  feeLimit: optional(t.string),

  /** Passphrase to decrypt the user key on the wallet */
  walletPassphrase: optional(t.string),

  /** The extended private key (alternative to walletPassphrase) */
  xprv: optional(t.string),

  /** Optional, private key in string form, if `walletPassphrase` is not available or encrypted private key is not stored by BitGo. */
  prv: optional(t.string),

  /** Message to attach to the transaction */
  message: optional(t.string),

  /** The unspent selection for the transaction will only consider unspents with at least this many confirmations to be used as inputs. Does not apply to change outputs unless used in combination with enforceMinConfirmsForChange. */
  minConfirms: optional(t.number),

  /** When set to true, will enforce minConfirms for change outputs. Defaults to false. */
  enforceMinConfirmsForChange: optional(t.boolean),

  /** Custodian transaction ID (for institutional custody integrations like Metamask) */
  custodianTransactionId: optional(t.string),

  /** Token name, defined in the BitGoJS Statics package. */
  tokenName: optional(t.string),

  // All SendManyOptions fields are also supported via the SendOptions index signature
  // Including these commonly used fields explicitly for better documentation:

  /**
   * (BTC only) The number of blocks required to confirm a transaction. You can use `numBlocks` to estimate the fee rate
   * by targeting confirmation within a given number of blocks. If both `feeRate` and `numBlocks` are absent, the
   * transaction defaults to 2 blocks for confirmation.
   *
   * Note: The `maxFeeRate` limits the fee rate generated by `numBlocks`.
   */
  numBlocks: optional(t.number),

  /**
   * Custom fee rate (in base units) per kilobyte (or virtual kilobyte). For example, satoshis per kvByte.
   *
   * If the `feeRate` is less than the minimum required network fee, then the minimum fee applies. For example,
   * 1000 sat/kvByte, a flat 1000 microAlgos, or a flat 10 drops of xrp. For XRP, the actual fee is usually
   * 4.5 times the open ledger fee.
   *
   * Note: The `feeRate` overrides the `maxFeeRate` and `minFeeRate`.
   */
  feeRate: optional(t.union([t.number, t.string])),

  /**
   * (UTXO only) Custom multiplier to the `feeRate`. The resulting fee rate is limited by the `maxFeeRate`.
   * For replace-by-fee (RBF) transactions (that include `rbfTxIds`), the `feeMultiplier` must be greater than 1,
   * since it's an absolute fee multiplier to the transaction being replaced.
   *
   * Note: The `maxFeeRate` limits the fee rate generated by `feeMultiplier`.
   */
  feeMultiplier: optional(t.number),

  /**
   * (BTC only) The maximum fee rate (in base units) per kilobyte (or virtual kilobyte). For example, satoshis per kvByte.
   * The `maxFeeRate` limits the fee rate generated by both `feeMultiplier` and `numBlocks`.
   *
   * Note: The `feeRate` overrides the `maxFeeRate`.
   */
  maxFeeRate: optional(t.number),

  /**
   * Defaults to 1000. Specifies the minimum count of good-sized unspents to maintain in the wallet.
   * Change splitting ceases when the wallet has `targetWalletUnspents` good-sized unspents.
   *
   * Note: Wallets that continuously send a high count of transactions will automatically split large change amounts
   * into multiple good-sized change outputs while they have fewer than `targetWalletUnspents` good-sized unspents
   * in their unspent pool. Breaking up large unspents helps to reduce the amount of unconfirmed funds in flight in
   * future transactions, and helps to avoid long chains of unconfirmed transactions. This is especially useful for
   * newly funded wallets or recently refilled send-only wallets.
   */
  targetWalletUnspents: optional(t.number),

  /** Ignore unspents smaller than this amount of base units (e.g. satoshis). For doge, only string is allowed. */
  minValue: optional(t.union([t.number, t.string])),

  /** Ignore unspents larger than this amount of base units (e.g. satoshis). For doge, only string is allowed. */
  maxValue: optional(t.union([t.number, t.string])),

  /**
   * A `sequenceId` is a unique and arbitrary wallet identifier applied to transfers and transactions at creation.
   * It is optional but highly recommended. With a `sequenceId` you can easily reference transfers and transactions—
   * for example, to safely retry sending. Because the system only confirms one send request per `sequenceId`
   * (and fails all subsequent attempts), you can retry sending without the risk of double spending.
   * The `sequenceId` is only visible to users on the wallet and is not shared publicly.
   */
  sequenceId: optional(t.string),

  /** (XRP only) Absolute max ledger the transaction should be accepted in, whereafter it will be rejected. */
  lastLedgerSequence: optional(t.number),

  /** (XRP only) Relative ledger height (in relation to the current ledger) that the transaction should be accepted in, whereafter it will be rejected. */
  ledgerSequenceDelta: optional(t.number),

  /** Custom gas price to be used for sending the transaction. Only for ETH and ERC20 tokens. */
  gasPrice: optional(t.number),

  /** Defaults to false. Set `true` to disable automatic change splitting. Also see: `targetWalletUnspents` */
  noSplitChange: optional(t.boolean),

  /** Used to explicitly specify the unspents to be used in the input set in the transaction. Each unspent should be in the form `prevTxId:nOutput`. */
  unspents: optional(t.array(t.string)),

  /** Optional metadata (only persisted in BitGo) to be applied to the transaction. Use this to add transaction-specific information such as the transaction's purpose or another identifier that you want to reference later. The value is shown in the UI in the transfer listing page. (length ≤ 256) */
  comment: optional(t.string),

  /** One-time password for 2FA */
  otp: optional(t.string),

  /** Specifies a custom destination address for the transaction's change output(s) (length ≤ 500) */
  changeAddress: optional(t.string),

  /** If true, allows using an external change address */
  allowExternalChangeAddress: optional(t.boolean),

  /** (DASH only) Specifies whether or not to use Dash's "InstantSend" feature when sending a transaction. */
  instant: optional(t.boolean),

  /** Extra transaction information for CSPR, EOS, HBAR, RUNE, STX, TON, XLM, and XRP. Required for XLM transactions. Note: For XRP this is the destination tag (DT). For CSPR this is the transfer ID. */
  memo: optional(MemoParams),

  /** Transfer ID for tracking purposes */
  transferId: optional(t.number),

  /** EIP-1559 fee parameters for Ethereum transactions */
  eip1559: optional(EIP1559Params),

  /** Custom gas limit to be used for sending the transaction. Only for ETH and ERC20 tokens. */
  gasLimit: optional(t.number),

  /**
   * Required for transactions from MPC wallets. "acceleration" speeds up transactions with a certain nonce by
   * adjusting the gas setting. "accountSet" is for XRP AccountSet transactions. "consolidate" combines multiple
   * UTXO inputs into fewer outputs. "enabletoken" is for SOL. "fanout" splits UTXO inputs into many smaller outputs
   * (UTXO coins only). "stakingLock" and "stakingUnlock" are for Stacks delegations. "transfer" is for native-asset
   * transfers. "trustline" is for Stellar trustline transactions.
   * Possible types include: [acceleration, accountSet, consolidate, enabletoken, fanout, stakingLock, stakingUnlock,
   * transfer, transfertoken, trustline].
   *
   * For AVAX, possible types include: `addValidator`, `export`, and `import`.
   * For XRP, possible types include: `payment` and `accountSet`. The default is `payment`.
   * For STX, type is required.
   */
  type: optional(t.string),

  /** (ETH, AVAXC and POLYGON) Set to true if funds to destination need to come from single sig address. */
  hop: optional(t.boolean),

  /** @deprecated Use `changeAddressType` instead. The type of address to create for change. One of `p2sh`, `p2shP2wsh`, `p2wsh`, or `p2tr`. */
  addressType: optional(t.string),

  /** The address type for the change address. One of `p2sh`, `p2shP2wsh`, `p2wsh`, `p2tr` or `p2trMusig2`. */
  changeAddressType: optional(t.string),

  /** [UTXO only] Format of the returned transaction hex serialization. `legacy` for serialized transaction in custom bitcoinjs-lib format. `psbt` for BIP174 serialized transaction. Defaults to `legacy`. */
  txFormat: optional(t.union([t.literal('legacy'), t.literal('psbt'), t.literal('psbt-lite')])),

  /** If set to false, sweep all funds including required minimums (e.g., DOT requires 1 DOT minimum) */
  keepAlive: optional(t.boolean),

  /** NFT collection ID (for NFT transfers) */
  nftCollectionId: optional(t.string),

  /** NFT ID (for NFT transfers) */
  nftId: optional(t.string),

  /** (DOT only) A nonce ID is a number used to protect private communications by preventing replay attacks. This is an advanced option where users can manually input a new nonce value in order to correct or fill in a missing nonce ID value. */
  nonce: optional(t.string),

  /** If true, only preview the transaction without sending */
  preview: optional(t.boolean),

  /** Receive address (for specific coins like ADA) */
  receiveAddress: optional(t.string),

  /** [UTXO only] An array of messages that you sign with the wallet keys using the BIP322 format. If passed, the recipients array must be empty. */
  messages: optional(
    t.array(
      t.type({
        address: t.string,
        message: t.string,
      })
    )
  ),

  /** The receive address from which funds will be withdrawn (supported for specific coins like ADA) */
  senderAddress: optional(t.string),

  /** The wallet ID of the sender wallet when different from current wallet (for BTC unstaking) */
  senderWalletId: optional(t.string),

  /** Close remainder to address (for specific blockchain protocols like Algorand) */
  closeRemainderTo: optional(t.string),

  /** Non-participation flag (for governance/staking protocols like Algorand) */
  nonParticipation: optional(t.boolean),

  /** Optional block this transaction is valid from. */
  validFromBlock: optional(t.number),

  /** Optional block this transaction is valid until. */
  validToBlock: optional(t.number),

  /** Optional parameter for UTXO coins to automatically reserve the unspents that are used in the build. Useful for Cold wallets. If using, must set `expireTime`. */
  reservation: optional(
    t.partial({
      expireTime: t.string,
      pendingApprovalId: t.string,
    })
  ),

  /** Enable offline transaction verification */
  offlineVerification: optional(t.boolean),

  /** Wallet contract address (for smart contract wallets) */
  walletContractAddress: optional(t.string),

  /** IDF (Identity Framework) signed timestamp */
  idfSignedTimestamp: optional(t.string),

  /** IDF user ID */
  idfUserId: optional(t.string),

  /** IDF version number */
  idfVersion: optional(t.number),

  /** Array of tokens to enable on the wallet */
  enableTokens: optional(t.array(TokenEnablement)),

  /** Low fee transaction ID (for CPFP - Child Pays For Parent) */
  lowFeeTxid: optional(t.string),

  /** Flag indicating if this is a TSS transaction */
  isTss: optional(t.boolean),

  /** API version to use for the transaction */
  apiVersion: optional(t.string),

  /** Custom Solana instructions to include in the transaction */
  solInstructions: optional(
    t.array(
      t.type({
        programId: t.string,
        keys: t.array(
          t.type({
            pubkey: t.string,
            isSigner: t.boolean,
            isWritable: t.boolean,
          })
        ),
        data: t.string,
      })
    )
  ),

  /** Solana versioned transaction data for building transactions with Address Lookup Tables */
  solVersionedTransactionData: optional(
    t.partial({
      versionedInstructions: t.array(
        t.type({
          programIdIndex: t.number,
          accountKeyIndexes: t.array(t.number),
          data: t.string,
        })
      ),
      addressLookupTables: t.array(
        t.type({
          accountKey: t.string,
          writableIndexes: t.array(t.number),
          readonlyIndexes: t.array(t.number),
        })
      ),
      staticAccountKeys: t.array(t.string),
      messageHeader: t.type({
        numRequiredSignatures: t.number,
        numReadonlySignedAccounts: t.number,
        numReadonlyUnsignedAccounts: t.number,
      }),
      recentBlockhash: t.string,
    })
  ),

  /** Custom transaction parameters for Aptos entry function calls */
  aptosCustomTransactionParams: optional(
    t.intersection([
      t.type({
        /** Module name - REQUIRED */
        moduleName: t.string,
        /** Function name - REQUIRED */
        functionName: t.string,
      }),
      t.partial({
        /** Type arguments - OPTIONAL */
        typeArguments: t.array(t.string),
        /** Function arguments - OPTIONAL */
        functionArguments: t.array(t.any),
        /** ABI - OPTIONAL */
        abi: t.any,
      }),
    ])
  ),

  /** Array of public keys for signing */
  pubs: optional(t.array(t.string)),

  /** Transaction request ID (for TSS wallets) */
  txRequestId: optional(t.string),

  /** Co-signer public key */
  cosignerPub: optional(t.string),

  /** Flag indicating if this is the last signature */
  isLastSignature: optional(t.boolean),

  /** Pre-built transaction object */
  txPrebuild: optional(t.any),

  /** Multisig type version (e.g., 'MPCv2') */
  multisigTypeVersion: optional(t.literal('MPCv2')),

  /** Pre-built transaction (hex string or serialized object) */
  prebuildTx: optional(t.union([t.string, t.any])),

  /** Verification options for the transaction */
  verification: optional(t.any),

  /** Transaction verification parameters (used for verifying transaction before signing) */
  verifyTxParams: optional(
    t.intersection([
      t.type({
        /** Transaction parameters to verify - REQUIRED when verifyTxParams is present */
        txParams: t.partial({
          /** Recipients for verification */
          recipients: t.array(
            t.intersection([
              t.type({
                /** Recipient address */
                address: t.string,
                /** Amount to send */
                amount: t.union([t.string, t.number]),
              }),
              t.partial({
                /** Token name */
                tokenName: t.string,
                /** Memo */
                memo: t.string,
              }),
            ])
          ),
          /** Wallet passphrase */
          walletPassphrase: t.string,
          /** Transaction type */
          type: t.string,
          /** Memo for verification */
          memo: MemoParams,
          /** Tokens to enable */
          enableTokens: t.array(TokenEnablement),
        }),
      }),
      t.partial({
        /** Verification options - OPTIONAL */
        verification: t.any,
      }),
    ])
  ),
} as const;

/**
 * This call allows you to create and send cryptocurrency to a destination address.
 *
 * @operationId express.wallet.sendcoins
 * @tag express
 */
export const PostSendCoins: HttpRoute<'post'> = httpRoute({
  path: '/api/v2/{coin}/wallet/{id}/sendcoins',
  method: 'POST',
  request: httpRequest({
    params: SendCoinsRequestParams,
    body: SendCoinsRequestBody,
  }),
  response: {
    /** Successfully sent transaction */
    200: SendManyResponse,
    /** Transaction requires approval (same structure as 200) */
    202: SendManyResponse,
    /** Invalid request or send operation fails */
    400: BitgoExpressError,
  },
});
