import * as t from 'io-ts';
import { httpRoute, httpRequest, optional } from '@api-ts/io-ts-http';
import { BitgoExpressError } from '../../schemas/error';
import { SendManyResponse } from './sendmany';

/**
 * Request path parameters for sweeping a wallet
 */
export const WalletSweepParams = {
  /** A cryptocurrency or token ticker symbol */
  coin: t.string,
  /** The wallet ID */
  id: t.string,
} as const;

/**
 * Request body for sweeping all funds from a wallet
 *
 * The sweep operation sends all available funds from the wallet to a specified address.
 * For UTXO coins, it uses the native /sweepWallet endpoint.
 * For account-based coins, it calculates the maximum spendable amount and uses sendMany.
 */
export const WalletSweepBody = {
  /** The destination address for the sweep transaction */
  address: t.string,

  /** Passphrase to decrypt the user key on the wallet */
  walletPassphrase: optional(t.string),

  /** Private key in string form, if walletPassphrase is not available */
  xprv: optional(t.string),

  /** Two factor auth code to enable sending the transaction */
  otp: optional(t.string),

  /** Custom fee rate (in base units) per kilobyte (or virtual kilobyte). For example, satoshis per kvByte */
  feeRate: optional(t.number),

  /** (BTC only) The maximum fee rate (in base units) per kilobyte (or virtual kilobyte). For example, satoshis per kvByte. The `maxFeeRate` limits the fee rate generated by both `feeMultiplier` and `numBlocks` */
  maxFeeRate: optional(t.number),

  /** Number of blocks to wait to confirm the transaction */
  feeTxConfirmTarget: optional(t.number),

  /** Use `allowPartialSweep: true` to sweep part of a wallet when there are too many unspents to empty the wallet in a single transaction. While the expected outcome of a single sweep call would usually be an empty wallet, using the allowPartialSweep option may leave some funds in the wallet. Making repeated calls with the allowPartialSweep option allows emptying wallets with many unspents without consolidating first */
  allowPartialSweep: optional(t.boolean),

  /** [UTXO only] Format of the returned transaction hex serialization. `legacy` for serialized transaction in custom bitcoinjs-lib format. `psbt` for BIP174 serialized transaction */
  txFormat: optional(t.union([t.literal('legacy'), t.literal('psbt'), t.literal('psbt-lite')])),
} as const;

/**
 * The sweep call spends the full balance of the wallet to the provided address. On UTXO coins, the sweep call will fail if the wallet has any unconfirmed funds, or if there are more unspents than can be sent with a single transaction.
 *
 * @operationId express.wallet.sweep
 * @tag Express
 */
export const PostWalletSweep = httpRoute({
  path: '/api/v2/{coin}/wallet/{id}/sweep',
  method: 'POST',
  request: httpRequest({
    params: WalletSweepParams,
    body: WalletSweepBody,
  }),
  response: {
    /** Successfully swept funds - same structure as sendMany */
    200: SendManyResponse,
    /** Invalid request or sweep operation fails */
    400: BitgoExpressError,
  },
});
