FROM rust:1.96.0-bookworm AS builder

ARG STACKS_CORE_COMMIT
RUN test -n "$STACKS_CORE_COMMIT" || (echo "STACKS_CORE_COMMIT not set" && false)

WORKDIR /stacks
COPY . .
RUN test "$(git rev-parse HEAD)" = "$STACKS_CORE_COMMIT" || \
    (echo "Stacks Core checkout is not at $STACKS_CORE_COMMIT" && false)
RUN apt-get update && apt-get install -y libclang-dev
RUN cargo build --locked --release --package stacks-node --package stacks-signer --bin stacks-node --bin stacks-signer

FROM debian:bookworm

COPY --from=builder /stacks/target/release/stacks-node /usr/local/bin/
COPY --from=builder /stacks/target/release/stacks-signer /usr/local/bin/
COPY --from=dobtc/bitcoin:25.1 /opt/bitcoin-*/bin /usr/local/bin

RUN apt-get update && apt-get install -y curl gettext-base jq
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /root
CMD ["stacks-node"]
