export const IOTA_ADDRESS_LENGTH = 64;
export const IOTA_TRANSACTION_DIGEST_LENGTH = 32;
export const IOTA_BLOCK_DIGEST_LENGTH = 32;
export const IOTA_SIGNATURE_LENGTH = 64;
export const IOTA_KEY_BYTES_LENGTH = 32; // Ed25519 public key is 32 bytes
export const MAX_INPUT_OBJECTS = 2048;
export const MAX_GAS_PAYMENT_OBJECTS = 256;
export const MAX_GAS_BUDGET = 50000000000;
export const MAX_GAS_PRICE = 100000;
export const MAX_RECIPIENTS = 256; // Maximum number of recipients in a transfer transaction
export const TRANSFER_TRANSACTION_COMMANDS = ['SplitCoins', 'MergeCoins', 'TransferObjects'];
