name: Manual release branch release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/v[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: write
jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@v0.13.1
    secrets: inherit
    with:
      run-build: true
      run-unit-tests: true
      publish: true
      publish-command: |
        ./bin/ci_validate_version.sh
        npm publish
