name: publish_canary

on:
  workflow_dispatch:

jobs:
  lint_test:
    uses: babylonlabs-io/.github/.github/workflows/reusable_node_lint_test.yml@v0.9.0
    secrets: inherit
    with:
      run-build: true
      run-unit-tests: true
      publish: true
      publish-command: 'npm publish --tag canary'
