import { IWallet, MessageStandardType } from '@bitgo/sdk-core';

export interface XdcKycMessageParams {
  account: string; // wallet Ethereum address (checksummed)
  timestamp: string; // ISO 8601, generated by caller at signing time
}

export interface XdcKycSignedMessage {
  kycAccount: string;
  kycMessage: string;
  kycSignature: string;
}

/**
 * Build the message string expected by the XinFin masternode IPFS API.
 * Format: "[XDCmaster KYC <timestamp>] Upload KYC for <account>"
 */
export function buildXdcKycMessage(params: XdcKycMessageParams): string {
  return `[XDCmaster KYC ${params.timestamp}] Upload KYC for ${params.account}`;
}

/**
 * Sign the XDC KYC message using the wallet's TSS key.
 * Calls wallet.signMessage() which routes through WP /msgrequests TSS ceremony.
 *
 * @param wallet - TSS wallet (must be XDC/TXDC)
 * @param account - wallet Ethereum address
 * @param walletPassphrase - user's wallet passphrase for TSS signing
 * @returns signed message object ready to send as staking-service request fields
 */
export async function signXdcKycMessage(
  wallet: IWallet,
  account: string,
  walletPassphrase: string
): Promise<XdcKycSignedMessage> {
  const timestamp = new Date().toISOString();
  const kycMessage = buildXdcKycMessage({ account, timestamp });

  const signed = await wallet.signMessage({
    message: {
      messageRaw: kycMessage,
      messageStandardType: MessageStandardType.EIP191,
    },
    walletPassphrase,
  });

  return {
    kycAccount: account,
    kycMessage,
    kycSignature: signed.signature,
  };
}
