import * as t from 'io-ts';
import { httpRoute, httpRequest, optional } from '@api-ts/io-ts-http';
import { BitgoExpressError } from '../../schemas/error';

export const DecryptRequestBody = {
  input: t.string,
  password: optional(t.string),
};

/**
 * Decrypt messages
 *
 * Decrypt a ciphertext generated by encrypt route with provided password
 *
 * @operationId express.decrypt
 * @tag Express
 * @public
 */
export const PostDecrypt = httpRoute({
  path: '/api/v2/decrypt',
  method: 'POST',
  request: httpRequest({
    body: DecryptRequestBody,
  }),
  response: {
    200: t.type({
      decrypted: t.string,
    }),
    404: BitgoExpressError,
  },
});
