import * as t from 'io-ts';
import { httpRoute, httpRequest, optional } from '@api-ts/io-ts-http';
import { BitgoExpressError } from '../../schemas/error';

/**
 * Request body for decrypting data
 *
 * Decrypt a ciphertext generated by encrypt route with provided password
 */
export const DecryptRequestBody = {
  /** The encrypted ciphertext string to decrypt */
  input: t.string,
  /** The password used as the decryption key (must match the password used to encrypt) */
  password: optional(t.string),
};

/**
 * Decrypt messages
 *
 * Decrypt a ciphertext generated by encrypt route with provided password
 *
 * @operationId express.decrypt
 * @tag Express
 * @public
 */
export const PostDecrypt = httpRoute({
  path: '/api/v[12]/decrypt',
  method: 'POST',
  request: httpRequest({
    body: DecryptRequestBody,
  }),
  response: {
    200: t.type({
      decrypted: t.string,
    }),
    404: BitgoExpressError,
  },
});
