export const amsTokenConfig = {
  'txlm:BST-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L': [
    {
      id: '47887cb5-98bb-4942-bd25-3ccca0847f36',
      fullName: 'BitGo Shield Token',
      name: 'txlm:BST-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L',
      prefix: '',
      suffix: 'BST',
      baseUnit: 'stroop',
      kind: 'crypto',
      family: 'xlm',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
      ],
      decimalPlaces: 7,
      asset: 'txlm:BST-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L',
      network: {
        type: 'testnet',
        name: 'StellarTestnet',
        family: 'xlm',
        explorerUrl: 'https://stellar.expert/explorer/testnet/tx/',
      },
      primaryKeyCurve: 'ed25519',
      domain: 'bitgo.com',
    },
  ],
  'tapt:usdt': [
    {
      id: '2695e728-96dd-46e6-9d01-bd0fdbe1ff38',
      fullName: 'USD Tether',
      name: 'tapt:usdt',
      prefix: '',
      suffix: 'TAPT:USDT',
      baseUnit: 'octa',
      kind: 'crypto',
      family: 'apt',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
        'tss',
        'tss-cold',
        'staking',
        'bulk-transaction',
        'bulk-staking-transaction',
        'supports-tokens',
        'enterprise-pays-fees',
        'tss-enterprise-pays-fees',
      ],
      decimalPlaces: 6,
      asset: 'tapt:usdt',
      network: {
        type: 'testnet',
        name: 'Testnet Apt',
        family: 'apt',
        explorerUrl: 'https://explorer.aptoslabs.com/txn/?network=testnet',
        accountExplorerUrl: 'https://explorer.aptoslabs.com/account/?network=testnet',
        blockExplorerUrl: 'https://explorer.aptoslabs.com/block/?network=testnet',
      },
      primaryKeyCurve: 'ed25519',
      assetId: '0xd5d0d561493ea2b9410f67da804653ae44e793c2423707d4f11edb2e38192050',
    },
  ],
  'talgo:JPT-162085446': [
    {
      id: '857994b1-3198-4649-a7a0-724a8620eb67',
      fullName: 'JPT',
      name: 'talgo:JPT-162085446',
      prefix: '',
      suffix: 'JPT',
      baseUnit: 'microAlgo',
      kind: 'crypto',
      family: 'algo',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
      ],
      decimalPlaces: 6,
      asset: 'talgo:JPT-162085446',
      network: {
        type: 'testnet',
        name: 'AlgorandTestnet',
        family: 'algo',
        explorerUrl: 'https://explorer.bitquery.io/algorand_testnet/tx/',
      },
      primaryKeyCurve: 'ed25519',
    },
  ],
  'teos:CHEX': [
    {
      id: '1c627bb5-4bee-4ab0-8bb6-3d535e17a769',
      fullName: 'Chintai',
      name: 'teos:CHEX',
      prefix: '',
      suffix: 'CHEX',
      baseUnit: 'eos',
      kind: 'crypto',
      family: 'eos',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
      ],
      decimalPlaces: 8,
      asset: 'chex',
      network: {
        type: 'testnet',
        name: 'EosTestnet',
        family: 'eos',
        explorerUrl: 'https://kylin.eosx.io/tx/',
      },
      primaryKeyCurve: 'secp256k1',
      contractName: 'testtoken113',
      contractAddress: 'testtoken113',
    },
  ],
  'hteth:gousd': [
    {
      id: '49ff49ea-3355-4717-bbb0-5e8f5cae2202',
      fullName: 'Hoodi Testnet GoUSD',
      name: 'hteth:gousd',
      prefix: '',
      suffix: 'HTETH:GOUSD',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'eth',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
      ],
      decimalPlaces: 6,
      asset: 'hteth:gousd',
      network: {
        type: 'testnet',
        name: 'Hoodi',
        family: 'eth',
        explorerUrl: 'https://hoodi.etherscan.io/tx/',
        accountExplorerUrl: 'https://hoodi.etherscan.io/address/',
        blockExplorerUrl: 'https://hoodi.etherscan.io/block/',
        chainId: 560048,
        batcherContractAddress: '0xb1b7e7cc1ecafbfd0771a5eb5454ab5b0356980d',
        forwarderFactoryAddress: '0x0e2874d6824fae4f61e446012317a9b86384bd8e',
        forwarderImplementationAddress: '0x7441f20a59be97011842404b9aefd8d85fd81aa6',
        nativeCoinOperationHashPrefix: 'ETHER',
        tokenOperationHashPrefix: 'ERC20',
      },
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0x65c959b9184b4f8c8633646d5dfd049d2ebc251a',
    },
  ],
  'txrp:xat': [
    {
      id: '155818c4-efda-4758-bb25-37c093b6dc02',
      fullName: 'XRP ATL Token',
      name: 'txrp:xat',
      prefix: '',
      suffix: 'TXRP:XAT',
      baseUnit: 'drop',
      kind: 'crypto',
      family: 'xrp',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
      ],
      decimalPlaces: 15,
      asset: 'txrp:xat',
      network: {
        type: 'testnet',
        name: 'XrpTestnet',
        family: 'xrp',
        explorerUrl: 'https://test.xrplexplorer.com/explorer/',
      },
      primaryKeyCurve: 'secp256k1',
      domain: 'xat.com',
      issuerAddress: 'rHy7UVhwM7Xgo4SoUTf5hE5yWKZKPEkxcL',
      currencyCode: '5841540000000000000000000000000000000000',
      contractAddress: 'rHy7UVhwM7Xgo4SoUTf5hE5yWKZKPEkxcL::5841540000000000000000000000000000000000',
    },
  ],
  'ttrx:usdt': [
    {
      id: '85a60a5a-88e3-45df-9e2c-dc6161b4c6b1',
      fullName: 'Tether USD',
      name: 'ttrx:usdt',
      prefix: '',
      suffix: 'TTRX:USDT',
      baseUnit: 'sun',
      kind: 'crypto',
      family: 'trx',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
      ],
      decimalPlaces: 6,
      asset: 'ttrx:usdt',
      network: {
        type: 'testnet',
        name: 'TrxTestnet',
        family: 'trx',
        accountExplorerUrl: 'https://shasta.tronscan.org/#/address/',
        explorerUrl: 'https://shasta.tronscan.org/#/transaction/',
        maxFeeLimit: '5000000000',
        contractCallFeeLimit: '100000000',
      },
      primaryKeyCurve: 'secp256k1',
      contractAddress: 'TG3XXyExBkPp9nzdajDZsozEu4BkaSJozs',
    },
  ],
  'tsol:slnd': [
    {
      id: 'de2477a1-d1db-4b58-a62d-aea4d00d8c0a',
      fullName: 'SOLEND',
      name: 'tsol:slnd',
      prefix: '',
      suffix: 'TSOL:SLND',
      baseUnit: 'lamport',
      kind: 'crypto',
      family: 'sol',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
        'tss',
        'tss-cold',
        'bulk-transaction',
      ],
      decimalPlaces: 9,
      asset: 'tsol:slnd',
      network: {
        type: 'testnet',
        name: 'SolTestnet',
        family: 'sol',
        explorerUrl: 'https://explorer.solana.com/tx/?cluster=devnet',
      },
      primaryKeyCurve: 'ed25519',
      tokenAddress: 'Ex6rHLLmvZoP9mpunMFvew424seSjPp5PQb5hDy8KJu6',
      contractAddress: 'Ex6rHLLmvZoP9mpunMFvew424seSjPp5PQb5hDy8KJu6',
    },
  ],
  'tstx:tsip6dp': [
    {
      id: 'ffa80cb4-dd2f-4729-9635-11071b9d8496',
      fullName: 'Test SIP10 Token 6 Decimals',
      name: 'tstx:tsip6dp',
      prefix: '',
      suffix: 'TSTX:TSIP6DP',
      baseUnit: 'micro-STX',
      kind: 'crypto',
      family: 'stx',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
        'multisig-cold',
        'alphanumeric-memo-id',
      ],
      decimalPlaces: 6,
      asset: 'tstx:tsip6dp',
      network: {
        type: 'testnet',
        name: 'StxTestnet',
        family: 'stx',
        explorerUrl: 'https://explorer.hiro.so/txid/?chain=testnet',
        sendmanymemoContractAddress: 'ST3F1X4QGV2SM8XD96X45M6RTQXKA1PZJZZCQAB4B',
        stakingContractAddress: 'ST000000000000000000002AMW42H',
      },
      primaryKeyCurve: 'secp256k1',
      assetId: 'STAG18E45W613FZ3H4ZMF6QHH426EXM5QTSAVWYH.tsip6dp-token::tsip6dp-token',
    },
  ],
  'tsui:deep': [
    {
      id: '0b8a7919-c37e-4be8-8338-7fc13c6c875e',
      fullName: 'Deepbook',
      name: 'tsui:deep',
      prefix: '',
      suffix: 'TSUI:DEEP',
      baseUnit: 'MIST',
      kind: 'crypto',
      family: 'sui',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
        'tss',
        'tss-cold',
        'bulk-transaction',
      ],
      decimalPlaces: 6,
      asset: 'tsui:deep',
      network: {
        type: 'testnet',
        name: 'Testnet Sui',
        family: 'sui',
        explorerUrl: 'https://explorer.sui.io/txblock/?network=testnet',
      },
      primaryKeyCurve: 'ed25519',
      packageId: '0x36dbef866a1d62bf7328989a10fb2f07d769f4ee587c0de4a0a256e57e0a58a8',
      module: 'deep',
      symbol: 'DEEP',
      contractAddress: '0x36dbef866a1d62bf7328989a10fb2f07d769f4ee587c0de4a0a256e57e0a58a8::deep::DEEP',
    },
  ],
  'thbar:usdc': [
    {
      id: '842c2119-3071-409d-b86f-49f0b46b676e',
      fullName: 'Testnet Hedera USD Coin',
      name: 'thbar:usdc',
      prefix: '',
      suffix: 'THBAR:USDC',
      baseUnit: 'tinybar',
      kind: 'crypto',
      family: 'hbar',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
      ],
      decimalPlaces: 6,
      asset: 'usdc',
      network: {
        type: 'testnet',
        name: 'HederaTestnet',
        family: 'hbar',
        explorerUrl: 'https://testnet.dragonglass.me/hedera/search?q=',
      },
      primaryKeyCurve: 'ed25519',
      nodeAccountId: '0.0.3',
      tokenId: '0.0.429274',
      contractAddress: '0.0.429274',
    },
  ],
  'tavaxc:bitgo': [
    {
      id: '463e36b1-8f92-40a3-9cb3-bd0aa7df8408',
      fullName: 'BitGo',
      name: 'tavaxc:bitgo',
      prefix: '',
      suffix: 'TAVAXC:BITGO',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'avaxc',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
      ],
      decimalPlaces: 8,
      asset: 'tavaxc:bitgo',
      network: {
        type: 'testnet',
        name: 'AvalancheCTestnet',
        family: 'avaxc',
        explorerUrl: 'https://subnets-test.avax.network/c-chain/tx/',
        accountExplorerUrl: 'https://subnets-test.avax.network/c-chain/address/',
        chainId: 43113,
      },
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0x3ad5f9119ca063189095784b9a7d2bf80fc24de6',
    },
  ],
  'tbsc:busd': [
    {
      id: 'b31aa2b5-8d8c-4ac1-b5e5-0f9d59377eab',
      fullName: 'Test Binance USD Token',
      name: 'tbsc:busd',
      prefix: '',
      suffix: 'TBSC:BUSD',
      baseUnit: 'jager',
      kind: 'crypto',
      family: 'bsc',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
        'bulk-transaction',
      ],
      decimalPlaces: 18,
      asset: 'tbsc:busd',
      network: {
        type: 'testnet',
        name: 'BinanceSmartChainTestnet',
        family: 'bsc',
        explorerUrl: 'https://testnet.bscscan.com/tx/',
        accountExplorerUrl: 'https://testnet.bscscan.com/address/',
        chainId: 97,
        nativeCoinOperationHashPrefix: '97',
        tokenOperationHashPrefix: '97-ERC20',
        batcherContractAddress: '0x6faf4b6bae3d4bf20c5d866c938f51992c63e825',
      },
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0xed24fc36d5ee211ea25a80239fb8c4cfd80f12ee',
    },
  ],
  'tpolygon:derc20': [
    {
      id: '09ba76d0-331e-4b75-bb75-739285c3e03a',
      fullName: 'Polygon Test ERC20',
      name: 'tpolygon:derc20',
      prefix: '',
      suffix: 'TPOLYGON:DERC20',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'polygon',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
        'bulk-transaction',
      ],
      decimalPlaces: 18,
      asset: 'tpolygon:derc20',
      network: {
        type: 'testnet',
        name: 'PolygonTestnet',
        family: 'polygon',
        explorerUrl: 'https://amoy.polygonscan.com/tx/',
        accountExplorerUrl: 'https://amoy.polygonscan.com/address/',
        chainId: 80002,
        forwarderFactoryAddress: '0x23223fd7cfc5f34b20f38ebb9a489e1ff3c084d1',
        forwarderImplementationAddress: '0xd4c24325b5ef514fbb1ecc76a9bb4dcb57a8341e',
        walletFactoryAddress: '0xe9c16033e01bf9f94bf9f99fc0fefcfb8b124992',
        walletImplementationAddress: '0xf8360c213e4f44cce03e48cb9281254de2a7a566',
        batcherContractAddress: '0xb1b7e7cc1ecafbfd0771a5eb5454ab5b0356980d',
        nativeCoinOperationHashPrefix: 'POLYGON',
        tokenOperationHashPrefix: 'POLYGON-ERC20',
      },
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0xfe4f5145f6e09952a5ba9e956ed0c25e3fa4c7f1',
    },
  ],
  'terc1155:bsctoken': [
    {
      id: 'f1506cf6-7949-4f2b-b87c-56d3483c7eea',
      fullName: 'Generic BSC ERC1155',
      name: 'terc1155:bsctoken',
      prefix: '',
      suffix: '',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'bsc',
      isToken: true,
      features: ['account-model', 'requires-big-number', 'valueless-transfer', 'transaction-data', 'genericToken'],
      decimalPlaces: 0,
      asset: 'erc721',
      network: {
        type: 'testnet',
        name: 'BinanceSmartChainTestnet',
        family: 'bsc',
        explorerUrl: 'https://testnet.bscscan.com/tx/',
        accountExplorerUrl: 'https://testnet.bscscan.com/address/',
        chainId: 97,
        nativeCoinOperationHashPrefix: '97',
        tokenOperationHashPrefix: '97-ERC20',
        batcherContractAddress: '0x6faf4b6bae3d4bf20c5d866c938f51992c63e825',
      },
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0xterc1155:bsctoken',
    },
  ],
};

export const amsTokenConfigWithCustomToken = {
  ...amsTokenConfig,
  'hteth:faketoken': [
    {
      id: '49ff49ea-3355-4717-bbb0-5e8f5cae2201',
      fullName: 'Hoodi Testnet fake token',
      name: 'hteth:faketoken',
      prefix: '',
      suffix: 'HTETH:FAKETOKEN',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'eth',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
        'bulk-transaction',
      ],
      decimalPlaces: 6,
      asset: 'hteth:faketoken',
      network: {
        type: 'testnet',
        name: 'Hoodi',
        family: 'eth',
        explorerUrl: 'https://hoodi.etherscan.io/tx/',
        accountExplorerUrl: 'https://hoodi.etherscan.io/address/',
        blockExplorerUrl: 'https://hoodi.etherscan.io/block/',
        chainId: 560048,
        batcherContractAddress: '0x3e1e5d78e44f15593b3b61ed278f12c27f0ff33e',
        forwarderFactoryAddress: '0x0e2874d6824fae4f61e446012317a9b86384bd8e',
        forwarderImplementationAddress: '0x7441f20a59be97011842404b9aefd8d85fd81aa6',
        nativeCoinOperationHashPrefix: 'ETHER',
        tokenOperationHashPrefix: 'ERC20',
        walletV4ForwarderFactoryAddress: '0x37996e762fa8b671869740c79eb33f625b3bf92a',
        walletV4ForwarderImplementationAddress: '0xd5fe1c1f216b775dfd30638fa7164d41321ef79b',
      },
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0x89a959b9184b4f8c8633646d5dfd049d2ebc983a',
    },
  ],
  ofcterc2: [
    {
      id: '055ebe86-72cc-4f0e-b46f-c517d8e36871',
      fullName: 'Test ERC Token2',
      name: 'ofcterc2',
      prefix: '',
      suffix: 'TERC',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'ofc',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-india',
      ],
      decimalPlaces: 18,
      asset: 'terc',
      network: {
        type: 'testnet',
        name: 'OfcTestnet',
        family: 'ofc',
      },
      primaryKeyCurve: 'secp256k1',
      addressCoin: 'teth',
      minimumDenomination: 1000000000000000000,
    },
  ],
};

export const incorrectAmsTokenConfig = {
  ...amsTokenConfig,
  'thbar:usdc': [
    {
      id: '842c2119-3071-409d-b86f-49f0b46b676e',
      fullName: 'Testnet Hedera USD Coin',
      name: 'thbar:usdc',
      prefix: '',
      suffix: 'THBAR:USDC',
      baseUnit: 'fakebar',
      kind: 'crypto',
      family: 'hbar',
      isToken: true,
      features: [
        'account-model',
        'requires-big-number',
        'valueless-transfer',
        'transaction-data',
        'custody',
        'custody-bitgo-trust',
        'custody-bitgo-mena-fze',
        'custody-bitgo-custody-mena-fze',
        'custody-bitgo-singapore',
        'custody-bitgo-korea',
        'custody-bitgo-europe-aps',
        'custody-bitgo-frankfurt',
        'custody-bitgo-india',
      ],
      decimalPlaces: 60,
      asset: 'usdc',
      network: {
        type: 'testnet',
        name: 'HederaTestnet',
        family: 'hbar',
        explorerUrl: 'https://testnet.dragonglass.me/hedera/search?q=',
      },
      primaryKeyCurve: 'ed25519',
      nodeAccountId: '0.0.3',
      tokenId: '0.0.429274',
      contractAddress: '0.0.429274',
    },
  ],
};

export const reducedAmsTokenConfig = {
  'hteth:faketoken': [
    {
      id: '49ff49ea-3355-4717-bbb0-5e8f5cae2201',
      fullName: 'Hoodi Testnet fake token',
      name: 'hteth:faketoken',
      prefix: '',
      suffix: 'HTETH:FAKETOKEN',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'eth',
      isToken: true,
      additionalFeatures: ['bulk-transaction'],
      excludedFeatures: ['custody-bitgo-korea'],
      decimalPlaces: 6,
      asset: 'hteth:faketoken',
      network: {
        name: 'Hoodi',
      },
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0x89a959b9184b4f8c8633646d5dfd049d2ebc983a',
    },
  ],
  ofcterc2: [
    {
      id: '055ebe86-72cc-4f0e-b46f-c517d8e36871',
      fullName: 'Test ERC Token2',
      name: 'ofcterc2',
      prefix: '',
      suffix: 'TERC',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'ofc',
      isToken: true,
      decimalPlaces: 18,
      asset: 'terc',
      additionalFeatures: [],
      excludedFeatures: [],
      network: {
        name: 'OfcTestnet',
      },
      primaryKeyCurve: 'secp256k1',
      addressCoin: 'teth',
      minimumDenomination: 1000000000000000000,
    },
  ],
};

export const amsTokenWithUnsupportedNetwork = {
  'hteth:faketoken': [
    {
      id: '49ff49ea-3355-4717-bbb0-5e8f5cae2201',
      fullName: 'Hoodi Testnet fake token',
      name: 'hteth:faketoken',
      prefix: '',
      suffix: 'HTETH:FAKETOKEN',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'eth',
      isToken: true,
      additionalFeatures: ['bulk-transaction'],
      excludedFeatures: ['custody-bitgo-korea'],
      decimalPlaces: 6,
      asset: 'hteth:faketoken',
      network: {
        name: 'FakeNetwork',
      },
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0x89a959b9184b4f8c8633646d5dfd049d2ebc983a',
    },
  ],
};

export const reducedTokenConfigForAllChains = {
  ...reducedAmsTokenConfig,
  'tarbeth:faketoken': [
    {
      id: 'd6a8869d-3da4-4b95-a9af-f2a059ca651a',
      fullName: 'Arbitrum Test Faketoken',
      name: 'tarbeth:faketoken',
      prefix: '',
      suffix: 'TARBETH:FAKETOKEN',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'arbeth',
      isToken: true,
      decimalPlaces: 18,
      asset: 'tarbeth:faketoken',
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0x143e1dae4f018ff86051a01d44a1b49b13704057',
      network: {
        name: 'ArbitrumTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: ['EIP1559'],
    },
  ],
  'tavaxc:faketoken': [
    {
      id: 'cd107316-6e78-4936-946f-70e8fd5d8045',
      fullName: 'Test Faketoken',
      name: 'tavaxc:faketoken',
      prefix: '',
      suffix: 'TAVAXC:FAKETOKEN',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'avaxc',
      isToken: true,
      decimalPlaces: 18,
      asset: 'avaxc:faketoken',
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0x0b9d5d9136855f6fec3c0993fee6e9ce8a297842',
      network: {
        name: 'AvalancheCTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'tbera:faketoken': [
    {
      id: '24af5e18-ab4b-43e5-80db-0ddb9beb01b1',
      fullName: 'Bera Testnet Faketoken',
      name: 'tbera:faketoken',
      prefix: '',
      suffix: 'TBERA:FAKETOKEN',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'bera',
      isToken: true,
      decimalPlaces: 18,
      asset: 'tbera:faketoken',
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0xbda130737bdd9618301681329bf2e46a016ff9ae',
      network: {
        name: 'BeraTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: ['EIP1559'],
    },
  ],
  'topeth:faketoken': [
    {
      id: 'fa6bc0a9-49f8-4516-88b7-cad6a62f1dc1',
      fullName: 'Opeth Faketoken',
      name: 'topeth:faketoken',
      prefix: '',
      suffix: 'TOPETH:FAKETOKEN',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'opeth',
      isToken: true,
      decimalPlaces: 18,
      asset: 'topeth:faketoken',
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0x75bb6dca2cd6f9a0189c478bbb8f7ee2fef07c79',
      network: {
        name: 'OptimismTestnet',
      },
      additionalFeatures: ['staking'],
      excludedFeatures: ['EIP1559'],
    },
  ],
  'tpolygon:faketoken': [
    {
      id: 'd6a8869d-3da4-4b95-a9af-f2a059ca651b',
      fullName: 'Polygon Test Faketoken',
      name: 'tpolygon:faketoken',
      prefix: '',
      suffix: 'TPOLYGON:FAKETOKEN',
      baseUnit: 'wei',
      kind: 'crypto',
      family: 'polygon',
      isToken: true,
      decimalPlaces: 18,
      asset: 'tpolygon:faketoken',
      primaryKeyCurve: 'secp256k1',
      contractAddress: '0xfe4f5145f6e09952a5ba9e956ed0c25e3fa4c7f7',
      network: {
        name: 'PolygonTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'ttrx:faketoken': [
    {
      id: '4ece7f15-a5c9-4302-8c82-787d7eb7e3c5',
      fullName: 'Test Tron Faketoken',
      name: 'ttrx:faketoken',
      prefix: '',
      suffix: 'TTRX:FAKETOKEN',
      baseUnit: 'sun',
      kind: 'crypto',
      family: 'trx',
      isToken: true,
      decimalPlaces: 8,
      asset: 'ttrx:faketoken',
      primaryKeyCurve: 'secp256k1',
      contractAddress: 'TGkfUshdbAiNj5G1mynp2meq2BfF6XSGPg',
      network: {
        name: 'TrxTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'tapt:faketoken': [
    {
      id: '2695e728-96dd-46e6-9d01-bd0fdbe1ff39',
      fullName: 'Aptos Faketoken',
      name: 'tapt:faketoken',
      prefix: '',
      suffix: 'TAPT:FAKETOKEN',
      baseUnit: 'octa',
      kind: 'crypto',
      family: 'apt',
      isToken: true,
      decimalPlaces: 6,
      asset: 'tapt:faketoken',
      primaryKeyCurve: 'ed25519',
      assetId: '0xd5d0d561493ea2b9410f67da804653ae44e793c2423707d4f11edb2e38192051',
      network: {
        name: 'Testnet Apt',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'tstx:faketoken': [
    {
      id: '74b5f05c-9cfa-45bf-b6a4-bc7f6dde37f8',
      fullName: 'Test Faketoken',
      name: 'tstx:faketoken',
      prefix: '',
      suffix: 'TSTX:FAKETOKEN',
      baseUnit: 'micro-STX',
      kind: 'crypto',
      family: 'stx',
      isToken: true,
      decimalPlaces: 8,
      asset: 'tstx:faketoken',
      primaryKeyCurve: 'secp256k1',
      assetId: 'ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT.fake-token::fake-token',
      network: {
        name: 'StxTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'talgo:faketoken-10458942': [
    {
      id: '0e20b757-3e62-4400-887d-caff117481c3',
      fullName: 'Faketoken',
      name: 'talgo:faketoken-10458942',
      alias: 'talgo:10458942',
      prefix: '',
      suffix: 'USDC',
      baseUnit: 'microAlgo',
      kind: 'crypto',
      family: 'algo',
      isToken: true,
      decimalPlaces: 6,
      asset: 'talgo:faketoken-10458942',
      primaryKeyCurve: 'ed25519',
      network: {
        name: 'AlgorandTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'thbar:faketoken': [
    {
      id: '842c2119-3071-409d-b86f-49f0b46b676a',
      fullName: 'Testnet Hedera Fake Token',
      name: 'thbar:faketoken',
      prefix: '',
      suffix: 'THBAR:FAKETOKEN',
      baseUnit: 'tinybar',
      kind: 'crypto',
      family: 'hbar',
      isToken: true,
      decimalPlaces: 6,
      asset: 'thbar:faketoken',
      primaryKeyCurve: 'ed25519',
      nodeAccountId: '0.0.3',
      tokenId: '0.0.429275',
      contractAddress: '0.0.429275',
      network: {
        name: 'HederaTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'tsol:faketoken': [
    {
      id: 'b98c5a7a-49c5-45f1-a6ee-b08dff596a7a',
      fullName: 'Solana fake token',
      name: 'tsol:faketoken',
      prefix: '',
      suffix: 'TSOL:FAKETOKEN',
      baseUnit: 'lamport',
      kind: 'crypto',
      family: 'sol',
      isToken: true,
      decimalPlaces: 9,
      asset: 'tsol:faketoken',
      primaryKeyCurve: 'ed25519',
      tokenAddress: 'D8YXLiwWQMibWRaxCTs9k6HwaYE6vtsbzK9KrQVMXU1L',
      contractAddress: 'D8YXLiwWQMibWRaxCTs9k6HwaYE6vtsbzK9KrQVMXU1L',
      programId: 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA',
      network: {
        name: 'SolTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'tsui:faketoken': [
    {
      id: '0b8a7919-c37e-4be8-8338-7fc13c6c875d',
      fullName: 'Fake token',
      name: 'tsui:faketoken',
      prefix: '',
      suffix: 'TSUI:FAKETOKEN',
      baseUnit: 'MIST',
      kind: 'crypto',
      family: 'sui',
      isToken: true,
      decimalPlaces: 6,
      asset: 'tsui:faketoken',
      primaryKeyCurve: 'ed25519',
      packageId: '0x36dbef866a1d62bf7328989a10fb2f07d769f4ee587c0de4a0a256e57e0a58a0',
      module: 'fake',
      symbol: 'FAKE',
      contractAddress: '0x36dbef866a1d62bf7328989a10fb2f07d769f4ee587c0de4a0a256e57e0a58a0::fake::FAKE',
      network: {
        name: 'Testnet Sui',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'ttao:faketoken': [
    {
      id: 'b8b5fded-65f8-49eb-8f83-ad97d08d07f1',
      fullName: 'Fake token',
      name: 'ttao:faketoken',
      prefix: '',
      suffix: 'TTAO:APEX',
      baseUnit: 'rao',
      kind: 'crypto',
      family: 'tao',
      isToken: true,
      decimalPlaces: 9,
      asset: 'ttao:apex',
      primaryKeyCurve: 'ed25519',
      subnetId: '1',
      network: {
        name: 'Testnet Tao',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'tpolyx:faketoken': [
    {
      id: 'a63b4f8d-84d6-45d3-bc67-625239e40812',
      fullName: 'Polymesh Fake token',
      name: 'tpolyx:faketoken',
      prefix: '',
      suffix: 'TPOLYX:FAKETOKEN',
      baseUnit: 'micropolyx',
      kind: 'crypto',
      family: 'polyx',
      isToken: true,
      decimalPlaces: 6,
      asset: 'tpolyx:faketoken',
      primaryKeyCurve: 'ed25519',
      ticker: 'FAKETOKEN',
      assetId: '0x780602887b358cf48989d0d9aa6c8d29',
      network: {
        name: 'PolymeshTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'txlm:FKE-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L': [
    {
      id: '9e1d4f1a-661b-4a51-b647-71f8c1330202',
      fullName: 'BitGo Fake token',
      name: 'txlm:FKE-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L',
      prefix: '',
      suffix: 'FKE',
      baseUnit: 'stroop',
      kind: 'crypto',
      family: 'xlm',
      isToken: true,
      decimalPlaces: 7,
      asset: 'txlm:FKE-GBQTIOS3XGHB7LVYGBKQVJGCZ3R4JL5E4CBSWJ5ALIJUHBKS6263644L',
      primaryKeyCurve: 'ed25519',
      domain: 'bitgo.com',
      network: {
        name: 'StellarTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
  'txrp:faketoken': [
    {
      id: '4c472d5f-0b9f-4086-9ff6-dcce51fce7fa',
      fullName: 'Fake token',
      name: 'txrp:faketoken',
      prefix: '',
      suffix: 'TXRP:FAKETOKEN',
      baseUnit: 'drop',
      kind: 'crypto',
      family: 'xrp',
      isToken: true,
      decimalPlaces: 15,
      asset: 'txrp:faketoken',
      primaryKeyCurve: 'secp256k1',
      domain: 'ripple.com',
      issuerAddress: 'rQhWct2fv4Vc4KRjRgMrxa8xPN9Zx9iLKA',
      currencyCode: '624C555344000000000000000000000000000000',
      contractAddress: 'rQhWct2fv4Vc4KRjRgMrxa8xPN9Zx9iLKA::624C555344000000000000000000000000000000',
      network: {
        name: 'XrpTestnet',
      },
      additionalFeatures: [],
      excludedFeatures: [],
    },
  ],
};
