name: Update Express API Documentation

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      target-ref:
        description: 'Git ref to checkout (defaults to workflow ref)'
        type: string
        required: false
        default: ${{ github.sha }}
      dry-run:
        description: 'If true, the PR will not be opened'
        type: boolean
        default: false
    secrets:
      VAULT_CF_ACCESS_CLIENT_SECRET:
        required: true

  workflow_dispatch:
    inputs:
      target-ref:
        description: 'Git ref to checkout'
        type: string
        required: false
      dry-run:
        description: 'Run in dry-run mode (no PR created)'
        type: boolean
        default: false

jobs:
  update-express-api-docs:
    name: Generate and update Express API documentation
    uses: BitGo/gha-dev-portal-updater/.github/workflows/generate-and-update.yml@WP-6251-add-support-for-yarn-to-dev-portal-updater-workflow
    with:
      target-ref: ${{ inputs.target-ref || github.sha }}
      service-name: express
      api-spec-title: "BitGo Express API"
      api-spec-file: modules/express/src/typedRoutes/api/index.ts
      codec-config-file: "modules/express/.openapi-generator.rc.js"
      dry-run: ${{ inputs.dry-run }}
    secrets:
      VAULT_CF_ACCESS_CLIENT_SECRET: ${{ secrets.VAULT_CF_ACCESS_CLIENT_SECRET }}
      